Repository SEED-platform/seed, pull requests merged in 2022-12, with the labels that each got.

#3623 Added the ability to create multiple compliance programs
  seed/migrations/0181_auto_20221202_0827.py
  seed/models/compliance_metrics.py
  seed/serializers/compliance_metrics.py
  seed/static/seed/js/controllers/data_view_controller.js
  seed/static/seed/js/controllers/insights_program_controller.js
  seed/static/seed/js/controllers/insights_property_controller.js
  seed/static/seed/js/controllers/program_setup_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/compliance_metric_service.js
  seed/static/seed/partials/accounts_nav.html
  seed/static/seed/partials/insights_program.html
  seed/static/seed/partials/insights_property.html
  seed/static/seed/partials/program_setup.html
  seed/static/seed/scss/style.scss
  seed/templates/seed/_header.html
  seed/tests/test_compliance_metrics_views.py
  seed/utils/properties.py
  seed/views/v3/compliance_metrics.py
Labels: BPS

#3650 2.16.0 release prep
  .github/release.yml
  CHANGELOG.md
  docs/source/developer_resources.rst
  docs/source/migrations.rst
  npm-shrinkwrap.json
  package.json
Labels: Ignore in release notes

#3654 Update contribution information and enforce PR labels
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/SEED_Contribution_Proposal_v1.0_2019-12-10.docx
  .github/SEED_Contribution_Proposal_v1.1_2022-12-05.docx
  .github/release.yml
  .github/workflows/pr-labels.yml
  docs/scripts/change_log.py
  docs/source/developer_resources.rst
Labels: Maintenance

#3658 Fix filtering on other inventory type
  seed/utils/inventory_filter.py
Labels: Bug

#3649 Refactor meter selection
  seed/static/seed/js/controllers/inventory_detail_meters_controller.js
  seed/static/seed/partials/inventory_detail_meters.html
Labels: Enhancement

#3666 Fix swagger loading the Meter endpoints
  seed/views/v3/meters.py
Labels: Bug

#3669 Disable sorting by derived column
  seed/models/columns.py
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/utils/inventory_filter.py
Labels: Enhancement

#3671 Sort legend on custom reports
  seed/static/seed/js/controllers/data_view_controller.js
Labels: Enhancement

#3678 Fix tooltip in insights legend
  seed/models/compliance_metrics.py
Labels: Bug

#3680 Support import of a csv file that has lots of spaces
  seed/lib/mcm/reader.py
Labels: Bug

#3709 Fix SEED to work with updated ESPM API, remove SEED ESPM API v2.1
  seed/api/v2_1/urls.py
  seed/tests/test_portfoliomanager.py
  seed/views/portfoliomanager.py
  seed/views/v3/portfolio_manager.py
Labels: Bug

#3699 Fix evaluate request
  seed/models/compliance_metrics.py
Labels: Bug

#3682 Fix legend
  seed/static/seed/js/controllers/data_view_controller.js
Labels: Enhancement

#3681 Update links for support
  docs/source/help.rst
  seed/static/seed/partials/contact.html
Labels: Documentation

#3702 Fix switching filter group
  seed/static/seed/js/controllers/inventory_list_controller.js
Labels: Bug

#3713 Add spinner to model deletion
  seed/data_importer/tests/data/example-data-properties-postal.xlsx
  seed/data_importer/tests/integration/test_data_import.py
  seed/lib/mcm/reader.py
  seed/static/seed/js/controllers/meter_deletion_modal_controller.js
  seed/utils/inventory_filter.py
Labels: Enhancement

#3714 Fix build and publish scripts by pinning version of Shapely
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .github/workflows/stale.yml
  requirements/base.txt
Labels: Do not publish

#3700 Delete Derived Columns Before Org
  seed/tasks.py
Labels: Bug

#3679 Nav property on click in property insight page
  seed/static/seed/js/controllers/insights_program_controller.js
  seed/static/seed/js/controllers/insights_property_controller.js
  seed/utils/properties.py
Labels: Feature

#3711 Update the BPS Sample Data AT Files
  seed/tests/data/bps/BPS_Sample_AT_11911.xml
  seed/tests/data/bps/BPS_Sample_AT_12227.xml
  seed/tests/data/bps/BPS_Sample_AT_17971.xml
  seed/tests/data/bps/BPS_Sample_AT_21368.xml
  seed/tests/data/bps/BPS_Sample_AT_21378.xml
  seed/tests/data/bps/BPS_Sample_AT_21381.xml
  seed/tests/data/bps/BPS_Sample_AT_21404.xml
  seed/tests/data/bps/BPS_Sample_AT_21405.xml
  seed/tests/data/bps/BPS_Sample_AT_21426.xml
  seed/tests/data/bps/README.md
Labels: Bug

#3710 Enter edit mode state on any change in custom report
  seed/static/seed/js/controllers/data_view_controller.js
Labels: Enhancement

#3715 Fix issue with evaluating compliance metric
  seed/models/compliance_metrics.py
Labels: Bug

#3719 Reorder the metric type drop down text in Program Configuration
  seed/migrations/0183_auto_20221216_1221.py
  seed/models/compliance_metrics.py
  seed/static/seed/partials/program_setup.html
Labels: Enhancement

#3716 ESPM formatting changes
  seed/data_importer/meters_parser.py
  seed/models/meters.py
  seed/tests/data/example-data-request-response-new-format.xlsx
  seed/tests/test_import_file_views.py
Labels: Maintenance

#3717 bump release versions
  docs/source/migrations.rst
  npm-shrinkwrap.json
  package.json
Labels: Do not publish

#3724 Resolve conflicts on main merge to develop
  docs/source/license.rst
  docs/source/mapping.rst
  docs/source/modules.rst
  seed/models/compliance_metrics.py
  seed/static/seed/js/controllers/insights_property_controller.js
  seed/static/seed/partials/program_setup.html
Labels: Do not publish

#3721 Release for 2.17.0
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/SEED_Contribution_Proposal_v1.0_2019-12-10.docx
  .github/SEED_Contribution_Proposal_v1.1_2022-12-05.docx
  .github/release.yml
  .github/workflows/ci.yml
  .github/workflows/pr-labels.yml
  .github/workflows/publish.yml
  .github/workflows/stale.yml
  docs/scripts/change_log.py
  docs/source/developer_resources.rst
  docs/source/help.rst
  docs/source/license.rst
  docs/source/mapping.rst
  docs/source/migrations.rst
  docs/source/modules.rst
  npm-shrinkwrap.json
  package.json
  requirements/base.txt
  seed/api/v2_1/urls.py
  seed/data_importer/meters_parser.py
  seed/data_importer/tests/data/example-data-properties-postal.xlsx
  seed/data_importer/tests/integration/test_data_import.py
  seed/lib/mcm/reader.py
  seed/migrations/0183_auto_20221216_1221.py
  seed/models/columns.py
  seed/models/compliance_metrics.py
  seed/models/meters.py
  seed/static/seed/js/controllers/data_view_controller.js
  seed/static/seed/js/controllers/insights_program_controller.js
  seed/static/seed/js/controllers/insights_property_controller.js
  seed/static/seed/js/controllers/inventory_detail_meters_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/meter_deletion_modal_controller.js
  seed/static/seed/partials/contact.html
  seed/static/seed/partials/inventory_detail_meters.html
  seed/static/seed/partials/program_setup.html
  seed/tasks.py
  seed/tests/data/bps/BPS_Sample_AT_11911.xml
  seed/tests/data/bps/BPS_Sample_AT_12227.xml
  seed/tests/data/bps/BPS_Sample_AT_17971.xml
  seed/tests/data/bps/BPS_Sample_AT_21368.xml
  seed/tests/data/bps/BPS_Sample_AT_21378.xml
  seed/tests/data/bps/BPS_Sample_AT_21381.xml
  seed/tests/data/bps/BPS_Sample_AT_21404.xml
  seed/tests/data/bps/BPS_Sample_AT_21405.xml
  seed/tests/data/bps/BPS_Sample_AT_21426.xml
  seed/tests/data/bps/README.md
  seed/tests/data/example-data-request-response-new-format.xlsx
  seed/tests/test_import_file_views.py
  seed/tests/test_portfoliomanager.py
  seed/utils/inventory_filter.py
  seed/utils/properties.py
  seed/views/portfoliomanager.py
  seed/views/v3/meters.py
  seed/views/v3/portfolio_manager.py
Labels: Do not publish

#3725 Fix stacked property points
  seed/static/seed/js/controllers/insights_property_controller.js
Labels: Bug

#3727 Fix filter group with extra column work on revised programs
  seed/utils/properties.py
Labels: Bug

#3730 Allow users to create columns
  seed/static/seed/js/controllers/column_settings_controller.js
  seed/static/seed/js/controllers/create_column_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/columns_service.js
  seed/static/seed/partials/column_settings.html
  seed/static/seed/partials/create_column_modal.html
  seed/templates/seed/_scripts.html
  seed/tests/test_column_views.py
  seed/views/v3/columns.py
Labels: Feature
