Repository SEED-platform/seed, pull requests merged in 2023-02, with the labels that each got.

#3806 Remove state population in create column
  seed/tests/test_column_views.py
  seed/views/v3/columns.py
Labels: Bug

#3783 Allow switching cycles in inventory detail page
  seed/api/v3/urls.py
  seed/serializers/properties.py
  seed/serializers/taxlots.py
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/inventory_service.js
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/tests/inventory_detail_controller.spec.js
  seed/static/seed/tests/property_detail_controller.spec.js
  seed/static/seed/tests/taxlot_detail_controller.spec.js
  seed/views/v3/property_views.py
  seed/views/v3/taxlot_views.py
Labels: Feature

#3816 Add more logging to the exception when a property state is missing an audit log
  .github/PULL_REQUEST_TEMPLATE.md
  config/urls.py
  seed/data_importer/match.py
Labels: Server Maintenance, Do not publish

#3822 Sort the dropdown of meter units
  seed/views/v3/organizations.py
Labels: Enhancement

#3824 Update Django to 3.2.17 and bump SEED to 2.17.2
  CHANGELOG.md
  docs/source/migrations.rst
  npm-shrinkwrap.json
  package.json
  requirements/base.txt
Labels: Maintenance

#3827 Release 2.17.2
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  config/urls.py
  docs/source/migrations.rst
  npm-shrinkwrap.json
  package.json
  requirements/base.txt
  seed/api/v3/urls.py
  seed/data_importer/match.py
  seed/models/data_views.py
  seed/serializers/properties.py
  seed/serializers/taxlots.py
  seed/static/seed/js/controllers/create_column_modal_controller.js
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/inventory_service.js
  seed/static/seed/partials/column_mappings.html
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/tests/inventory_detail_controller.spec.js
  seed/static/seed/tests/property_detail_controller.spec.js
  seed/static/seed/tests/taxlot_detail_controller.spec.js
  seed/tests/test_column_views.py
  seed/views/v3/columns.py
  seed/views/v3/organizations.py
  seed/views/v3/property_views.py
  seed/views/v3/taxlot_views.py
Labels: Do not publish

#3832 Change "Program Configuration" to "Program Setup"
  seed/static/seed/js/controllers/program_setup_controller.js
  seed/static/seed/partials/program_setup.html
Labels: Enhancement

#3838 Get audit date and audit date type from buildingsync files
  seed/building_sync/building_sync.py
  seed/building_sync/mappings.py
  seed/building_sync/tests/test_buildingsync.py
Labels: Enhancement

#3841 Improve inventory document upload process
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/document_upload_modal.html
Labels: Enhancement

#3856 Fix ESPM xml report import
  seed/tests/data/portfolio-manager-report.xml
  seed/tests/test_portfoliomanager.py
  seed/views/v3/portfolio_manager.py
Labels: Bug

#3865 Update mypy to version 1.0
  docs/scripts/export_issues_to_csv.py
  mypy.ini
  requirements/test.txt
  seed/models/derived_columns.py
  tox.ini
Labels: Maintenance

#3757 Add CRUD to MeterReading
  seed/api/v3/urls.py
  seed/data_importer/utils.py
  seed/lib/superperms/orgs/migrations/0012_auto_20200327_1213.py
  seed/lib/superperms/orgs/models.py
  seed/lib/superperms/orgs/permissions.py
  seed/migrations/0184_alter_meter_type.py
  seed/models/meters.py
  seed/serializers/meter_readings.py
  seed/serializers/meters.py
  seed/tests/test_meter_views.py
  seed/utils/meters.py
  seed/views/v3/meter_readings.py
  seed/views/v3/properties.py
Labels: Feature

#3743 Remove project and compliance models
  CHANGELOG.md
  docs/source/aws.rst
  docs/source/linux.rst
  docs/source/modules/seed.models.rst
  docs/source/modules/seed.urls.rst
  docs/source/modules/seed.utils.rst
  docs/source/modules/seed.views.rst
  seed/api/v2/urls.py
  seed/docs/faq/features/get-general-info.md
  seed/migrations/0185_auto_20230112_0922.py
  seed/models/__init__.py
  seed/models/models.py
  seed/models/notes.py
  seed/models/projects.py
  seed/serializers/projects.py
  seed/tests/api/test_modules.py
  seed/tests/test_project_views.py
  seed/tests/tests.py
  seed/views/projects.py
Labels: Maintenance

#3848 Fix importing of GeoJSON property footprints
  seed/lib/mcm/reader.py
  seed/lib/mcm/tests/test_reader_jsonparser.py
Labels: Bug

#3851 Update GeoJSON export format with GeometryCollections and remove crs
  seed/serializers/meters.py
  seed/tests/test_tax_lot_property.py
  seed/views/v3/tax_lot_properties.py
Labels: Enhancement

#3866 Fix Nginx Security
  docker/nginx-seed.conf
Labels: Maintenance

#3867 Fix clickable header
  seed/static/seed/scss/style.scss
Labels: Bug

#3868 Add export to meters and meter readings
  seed/static/seed/js/controllers/inventory_detail_meters_controller.js
  seed/static/seed/partials/home.html
  seed/static/seed/partials/inventory_detail_meters.html
  seed/static/seed/scss/style.scss
Labels: Feature

#3870 Prep release 2.17.3
  CHANGELOG.md
  docs/source/migrations.rst
  npm-shrinkwrap.json
  package.json
Labels: Do not publish

#3871 Release 2.17.3
  CHANGELOG.md
  docker/nginx-seed.conf
  docs/source/aws.rst
  docs/source/linux.rst
  docs/source/migrations.rst
  docs/source/modules/seed.models.rst
  docs/source/modules/seed.urls.rst
  docs/source/modules/seed.utils.rst
  docs/source/modules/seed.views.rst
  npm-shrinkwrap.json
  package.json
  requirements/base.txt
  seed/api/v2/urls.py
  seed/api/v3/urls.py
  seed/building_sync/building_sync.py
  seed/building_sync/mappings.py
  seed/building_sync/tests/test_buildingsync.py
  seed/data_importer/utils.py
  seed/docs/faq/features/get-general-info.md
  seed/lib/mcm/reader.py
  seed/lib/mcm/tests/test_reader_jsonparser.py
  seed/lib/superperms/orgs/migrations/0012_auto_20200327_1213.py
  seed/lib/superperms/orgs/models.py
  seed/lib/superperms/orgs/permissions.py
  seed/migrations/0184_alter_meter_type.py
  seed/migrations/0185_auto_20230112_0922.py
  seed/models/__init__.py
  seed/models/meters.py
  seed/models/models.py
  seed/models/notes.py
  seed/models/projects.py
  seed/serializers/meter_readings.py
  seed/serializers/meters.py
  seed/serializers/projects.py
  seed/static/seed/js/controllers/inventory_detail_meters_controller.js
  seed/static/seed/js/controllers/program_setup_controller.js
  seed/static/seed/partials/home.html
  seed/static/seed/partials/inventory_detail_meters.html
  seed/static/seed/partials/program_setup.html
  seed/static/seed/scss/style.scss
  seed/tests/api/test_modules.py
  seed/tests/data/portfolio-manager-report.xml
  seed/tests/test_meter_views.py
  seed/tests/test_portfoliomanager.py
  seed/tests/test_project_views.py
  seed/tests/test_tax_lot_property.py
  seed/tests/tests.py
  seed/utils/meters.py
  seed/views/projects.py
  seed/views/v3/meter_readings.py
  seed/views/v3/portfolio_manager.py
  seed/views/v3/properties.py
  seed/views/v3/tax_lot_properties.py
Labels: Do not publish

#3853 Open New Tab on Insight Property Click
  seed/static/seed/js/controllers/insights_property_controller.js
Labels: Enhancement

#3873 Update nginx security
  docker/nginx-seed.conf
Labels: Maintenance

#3875 Prep release for 2.17.4
  CHANGELOG.md
  docs/source/developer_resources.rst
  docs/source/index.rst
  docs/source/matching.rst
  docs/source/migrations.rst
  docs/source/modules.rst
  docs/source/modules/seed.tests.rst
  docs/source/setup_osx.rst
  npm-shrinkwrap.json
  package.json
  seed/models/columns.py
  seed/utils/api.py
Labels: Do not publish

#3878 Release 2.17.4
  CHANGELOG.md
  docker/nginx-seed.conf
  docs/source/developer_resources.rst
  docs/source/index.rst
  docs/source/matching.rst
  docs/source/migrations.rst
  docs/source/modules.rst
  docs/source/modules/seed.tests.rst
  docs/source/setup_osx.rst
  npm-shrinkwrap.json
  package.json
  seed/models/columns.py
  seed/static/seed/js/controllers/insights_property_controller.js
  seed/utils/api.py
Labels: Do not publish
