Repository SEED-platform/seed, pull requests merged in 2023-11, with the labels that each got.

#4377 Provide environment variable to disable wait-for-it condition in deployments
  docker/start_celery_docker.sh
  docker/start_uwsgi_docker.sh
Labels: Feature

#4370 Display error message on failed invite
  seed/static/seed/js/controllers/new_member_modal_controller.js
  seed/static/seed/partials/new_member_modal.html
Labels: Feature, Acct. Hierarchy

#4374 Add healthcheck to docker web container
  docker-compose.local.yml
  docker-compose.yml
Labels: Feature

#4302 Ah permissions/ubid view set
  seed/lib/superperms/orgs/decorators.py
  seed/tests/test_ubids.py
  seed/utils/ubid.py
  seed/views/v3/ubid.py
Labels: Feature, Acct. Hierarchy

#4382 Updated salesforce pg_restore docs
  docs/source/developer_resources.rst
  seed/utils/salesforce.py
Labels: Documentation

#4392 Fix upload
  seed/lib/superperms/orgs/decorators.py
Labels: Bug

#4271 Disallow nonroot user from CUD column list profile
  seed/docs/views.py
  seed/static/seed/js/controllers/insights_property_controller.js
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/inventory_list_legacy_controller.js
  seed/static/seed/js/controllers/menu_controller.js
  seed/static/seed/js/controllers/update_item_labels_modal_controller.js
  seed/static/seed/js/services/user_service.js
  seed/static/seed/partials/inventory_detail_settings.html
  seed/static/seed/partials/inventory_list.html
  seed/static/seed/partials/inventory_list_legacy.html
  seed/static/seed/partials/inventory_settings.html
  seed/static/seed/partials/update_item_labels_modal.html
  seed/static/seed/tests/update_item_labels_controller.spec.js
  seed/templates/seed/base.html
  seed/tests/test_account_views.py
  seed/views/main.py
Labels: Feature, Acct. Hierarchy

#4395 Squash migrations
  seed/data_importer/migrations/0019_importrecord_access_level_instance.py
  seed/migrations/0211_auto_add_props_to_tree.py
  seed/migrations/0211_auto_add_props_to_tree_squashed_0213_analysis_access_level_instance.py
  seed/migrations/0212_auto_20230623_1556.py
  seed/migrations/0213_analysis_access_level_instance.py
Labels: Feature, Acct. Hierarchy

#4383 Fix analysis bug
  seed/lib/superperms/orgs/decorators.py
  seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
  seed/static/seed/js/services/analyses_service.js
Labels: Bug, Acct. Hierarchy

#4410 Fix co2 analysis column naming
  seed/analysis_pipelines/co2.py
Labels: Bug, Analyses

#4411 Audit Template Report Submission Endpoint
  .cspell.json
  seed/audit_template/audit_template.py
  seed/tests/test_audit_template.py
  seed/views/main.py
  seed/views/v3/audit_template.py
Labels: Feature

#4403 Upgrade table
  seed/static/seed/js/controllers/inventory_summary_controller.js
  seed/static/seed/partials/inventory_summary.html
Labels: Feature

#4387 Salesforce scheduling issues
  seed/static/seed/partials/organization_settings.html
  seed/utils/salesforce.py
  seed/views/v3/salesforce_configs.py
Labels: Bug

#4384 Property Insights UI Enhancements
  seed/static/seed/js/controllers/insights_property_controller.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/insights_property.html
  seed/static/seed/scss/style.scss
Labels: Enhancement, SCEP

#4417 4137 fix anl error message
  seed/lib/superperms/orgs/models.py
  seed/static/seed/js/controllers/organization_add_access_level_modal_controller.js
Labels: Feature, Acct. Hierarchy

#4385 Custom Report Name Field Location
  seed/static/seed/js/controllers/data_view_controller.js
  seed/static/seed/partials/data_view.html
Labels: Bug, SCEP
