Repository SEED-platform/seed, pull requests merged in 2023-12, with the labels that each got.

#4386 Add distance to target in table under property insights graph
  seed/static/seed/js/controllers/insights_property_controller.js
  seed/static/seed/partials/insights_property.html
Labels: Enhancement, SCEP

#4402 Remove chart
  seed/static/seed/js/controllers/inventory_summary_controller.js
  seed/static/seed/partials/inventory_summary.html
Labels: Feature, Acct. Hierarchy

#4428 Order cycles by start date on program setup
  seed/static/seed/js/controllers/program_setup_controller.js
Labels: Bug

#4420 Populate default report using cycles
  seed/static/seed/js/controllers/export_report_modal_controller.js
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/static/seed/js/services/inventory_reports_service.js
  seed/static/seed/partials/inventory_reports.html
  seed/static/seed/scss/style.scss
  seed/tests/test_reports.py
  seed/views/v3/organizations.py
Labels: Enhancement

#4423 Add count to default reports
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/views/v3/organizations.py
Labels: Feature

#4425 Property Insights Tooltip Refinement
  seed/static/seed/js/controllers/insights_property_controller.js
Labels: Bug, SCEP

#4434 Forgo evil evil serializer
  seed/views/v3/analyses.py
Labels: Enhancement

#4438 Additional analyses performance improvement
  seed/models/analysis_property_views.py
  seed/views/v3/analysis_views.py
Labels: Enhancement

#4439 Release 2.21.0
  CHANGELOG.md
  docs/source/migrations.rst
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  package-lock.json
  package.json
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  vendors/package-lock.json
Labels: Do not publish

#4435 Fix ali tree permissions
  seed/lib/superperms/orgs/models.py
  seed/tests/test_organization_access_levels.py
  seed/views/v3/access_levels.py
Labels: Bug, Acct. Hierarchy

#4441 sort cycles by start_date on property insights page
  seed/models/compliance_metrics.py
Labels: Enhancement

#4442 display x axis label for ranked distance to compliance
  seed/static/seed/js/controllers/insights_property_controller.js
Labels: Bug

#4443 Add permissions to BuildingFile
  seed/models/building_file.py
  seed/tests/test_building_file.py
  seed/views/v3/building_files.py
Labels: Enhancement, Acct. Hierarchy

#4444 Fixed FontAwesome v6.5 alignment
  seed/static/seed/partials/home.html
  seed/static/seed/scss/style.scss
  seed/templates/seed/_sidebar.html
  vendors/package-lock.json
  vendors/package.json
Labels: Enhancement

#4451 FIx 4450
  seed/static/seed/js/controllers/organization_access_level_tree_controller.js
Labels: Bug, Acct. Hierarchy
