Repository SEED-platform/seed, pull requests merged in 2023-08, with the labels that each got.

#4169 Add Open Street Map to CSP rules
  docker/nginx/seed-csp.conf
Labels: Bug

#4159 add error handling for sf edge case
  seed/utils/salesforce.py
Labels: Bug

#4125 Remove ID from inventory document display name
  seed/static/seed/partials/inventory_detail.html
Labels: Maintenance

#4174 Set the MEDIA_ROOT path back to original value during test
  .cspell/custom-dictionary-workspace.txt
  seed/tests/test_media.py
Labels: Do not publish

#4182 Ah/fix tests
  seed/data_importer/match.py
  seed/lib/superperms/orgs/migrations/0028_auto_20230413_1250.py
  seed/migrations/0204_auto_add_props_to_tree.py
Labels: Bug

#4163 Add permission LabelViewSet
  seed/tests/test_labels_api_views.py
  seed/views/v3/labels.py
Labels: Feature, Acct. Hierarchy

#4161 Permission tests for salesforce workflow
  seed/tests/test_property_views.py
  seed/tests/test_salesforce_views.py
  seed/views/v3/properties.py
Labels: Enhancement, Acct. Hierarchy

#4157 Add AH Permissions to PropertyViewSet
  seed/tests/test_property_views.py
  seed/tests/test_salesforce_views.py
  seed/tests/util.py
  seed/utils/inventory_filter.py
  seed/utils/labels.py
  seed/utils/match.py
  seed/utils/properties.py
  seed/views/properties.py
  seed/views/v3/properties.py
Labels: Feature, Acct. Hierarchy

#4193 Add permissions to MeterReadingViewSet
  seed/tests/test_meter_views.py
Labels: Feature, Acct. Hierarchy

#4189 Add permissions to datasetviewset
  seed/lib/superperms/orgs/decorators.py
  seed/tests/test_views.py
  seed/views/v3/datasets.py
Labels: Feature, Acct. Hierarchy

#4183 Add permissions to PropertyMeasuresViewSet
  seed/lib/superperms/orgs/decorators.py
  seed/static/seed/js/services/property_measure_service.js
  seed/static/seed/js/services/scenario_service.js
  seed/tests/test_property_measures.py
  seed/views/v3/property_measures.py
Labels: Feature, Acct. Hierarchy

#4191 Ah permissions/note view set
  seed/lib/superperms/orgs/decorators.py
  seed/tests/test_note_views.py
  seed/tests/util.py
  seed/views/v3/import_files.py
  seed/views/v3/notes.py
Labels: Feature, Acct. Hierarchy

#4206 Optimize list analyses endpoint
  seed/serializers/analysis_property_views.py
  seed/static/seed/js/controllers/analyses_controller.js
  seed/static/seed/partials/analyses.html
  seed/views/v3/analyses.py
Labels: Enhancement

#4211 Fix 179d ESPM update endpoint to run in foreground with Celery enabled
  seed/data_importer/tasks.py
  seed/lib/xml_mapping/mapper.py
  seed/views/v3/properties.py
Labels: Feature
