Repository SEED-platform/seed, pull requests merged in 2023-03, with the labels that each got.

#3840 Implement Salesforce integration
  .github/workflows/ci.yml
  README.md
  bin/apitest_start_server.sh
  bin/protractor_start_server.sh
  bin/start-seed.sh
  bin/start_celery.sh
  config/settings/common.py
  config/settings/docker_dev.py
  config/settings/test.py
  docker/start_celery_docker.sh
  docs/scripts/export_issues_to_csv.py
  docs/source/aws.rst
  docs/source/linux.rst
  docs/source/setup_osx.rst
  mypy.ini
  requirements/base.txt
  requirements/test.txt
  seed/api/v3/urls.py
  seed/lib/superperms/orgs/migrations/0024_salesforce_configurations.py
  seed/lib/superperms/orgs/models.py
  seed/migrations/0186_salesforce_configs.py
  seed/models/__init__.py
  seed/models/derived_columns.py
  seed/models/salesforce_configs.py
  seed/models/salesforce_mappings.py
  seed/serializers/organizations.py
  seed/serializers/salesforce_configs.py
  seed/serializers/salesforce_mappings.py
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/organization_settings_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/inventory_service.js
  seed/static/seed/js/services/salesforce_config_service.js
  seed/static/seed/js/services/salesforce_mapping_service.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/partials/inventory_list.html
  seed/static/seed/partials/organization_settings.html
  seed/static/seed/scss/style.scss
  seed/static/seed/tests/settings_controller.spec.js
  seed/tasks.py
  seed/templates/seed/_scripts.html
  seed/templates/seed/salesforce_update_errors.html
  seed/tests/test_salesforce_views.py
  seed/utils/encrypt.py
  seed/utils/salesforce.py
  seed/views/v3/organizations.py
  seed/views/v3/properties.py
  seed/views/v3/salesforce_configs.py
  seed/views/v3/salesforce_mappings.py
  tox.ini
  vendors/package-lock.json
Labels: Feature

#3815 Add ability to edit and delete scenarios and measures
  seed/api/v3/urls.py
  seed/models/property_measures.py
  seed/models/scenarios.py
  seed/serializers/measures.py
  seed/static/seed/partials/inventory_detail.html
  seed/tests/test_property_measures.py
  seed/tests/test_scenarios.py
  seed/utils/api_schema.py
  seed/utils/viewsets.py
  seed/views/v3/property_measures.py
  seed/views/v3/property_scenarios.py
Labels: Enhancement

#3900 Add option to export meter data in GeoJSON
  seed/serializers/meter_readings.py
  seed/static/seed/js/controllers/export_inventory_modal_controller.js
  seed/static/seed/partials/export_inventory_modal.html
  seed/views/v3/meter_readings.py
  seed/views/v3/tax_lot_properties.py
Labels: Feature

#3858 Filter cycle specific labels on inventory list
  seed/search.py
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/services/label_service.js
  seed/utils/labels.py
  seed/views/v3/properties.py
  seed/views/v3/taxlots.py
Labels: Bug

#3864 Update Evaluate Permissions
  seed/static/seed/js/controllers/data_view_controller.js
  seed/static/seed/js/controllers/insights_program_controller.js
  seed/static/seed/js/controllers/insights_property_controller.js
  seed/static/seed/js/controllers/program_setup_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/partials/accounts_nav.html
  seed/static/seed/partials/data_view.html
  seed/static/seed/partials/insights_program.html
  seed/static/seed/partials/insights_property.html
  seed/static/seed/partials/program_setup.html
  seed/views/v3/data_views.py
Labels: Enhancement

#3895 select cycles instead of start/end dates
  docs/source/translation.rst
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  script/get_angular_translations.sh
  script/get_python_translations.sh
  seed/migrations/0187_update_compliance_metric_cycles.py
  seed/models/compliance_metrics.py
  seed/serializers/compliance_metrics.py
  seed/static/seed/js/controllers/insights_property_controller.js
  seed/static/seed/js/controllers/program_setup_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/program_setup.html
  seed/tests/test_compliance_metrics_views.py
Labels: Enhancement

#3820 Specify cycle in eui analysis
  seed/analysis_pipelines/eui.py
  seed/static/seed/js/controllers/analyses_controller.js
  seed/static/seed/js/controllers/analysis_details_controller.js
  seed/static/seed/js/controllers/inventory_detail_analyses_controller.js
  seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/inventory_list_legacy_controller.js
  seed/static/seed/partials/analyses.html
  seed/static/seed/partials/analysis_card.html
  seed/static/seed/partials/analysis_details.html
  seed/static/seed/partials/inventory_detail_analyses_modal.html
  seed/static/seed/scss/style.scss
  seed/tests/test_analysis_pipelines.py
Labels: Enhancement

#3881 Migrate BETTER API from V1 to V2
  config/settings/docker_dev.py
  seed/analysis_pipelines/better/buildingsync.py
  seed/analysis_pipelines/better/client.py
  seed/analysis_pipelines/better/helpers.py
  seed/analysis_pipelines/better/pipeline.py
  seed/models/analyses.py
  seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
  seed/static/seed/js/controllers/organization_settings_controller.js
  seed/static/seed/js/services/analyses_service.js
  seed/static/seed/partials/analysis_details.html
  seed/static/seed/partials/inventory_detail_analyses_modal.html
  seed/static/seed/partials/organization_settings.html
  seed/views/v3/analyses.py
Labels: Maintenance

#3924 Fix deletion of new custom report
  seed/static/seed/js/controllers/data_view_controller.js
  seed/static/seed/partials/data_view.html
Labels: Bug

#3925 Fix saving BETTER/Salesforce data for non-active orgs
  seed/static/seed/js/controllers/organization_settings_controller.js
  seed/static/seed/js/services/analyses_service.js
  seed/static/seed/js/services/salesforce_config_service.js
  seed/static/seed/js/services/salesforce_mapping_service.js
Labels: Bug

#3930 Fix GitHub Actions Masking
  .github/workflows/ci.yml
Labels: Bug

#3928 adding >= and <= to display
  seed/static/seed/partials/program_setup.html
Labels: Bug

#3926 Fix custom reports download button
  seed/static/seed/partials/data_view.html
Labels: Bug

#3927 Updated the meter import process to work with latest format from EnergyStar Portfolio Manager
  seed/data_importer/meters_parser.py
  seed/data_importer/tests/data/example-pm-data-request-with-meters-new-format.xlsx
Labels: Bug

#3931 Fix active nav for deep URLs
  seed/static/seed/js/controllers/data_view_controller.js
  seed/static/seed/js/controllers/program_setup_controller.js
  seed/static/seed/partials/accounts_nav.html
  seed/static/seed/partials/insights_nav.html
Labels: Bug

#3934 Make test_compliance_metric_retrieve_endpoint deterministic
  seed/serializers/compliance_metrics.py
  seed/tests/test_compliance_metrics_views.py
Labels: Bug

#3936 Fix custom report creation reload
  seed/static/seed/js/controllers/data_view_controller.js
  seed/static/seed/partials/data_view.html
Labels: Bug

#3860 Add labels button on property insights page
  seed/static/seed/js/controllers/insights_property_controller.js
  seed/static/seed/partials/insights_property.html
  seed/static/seed/scss/style.scss
Labels: Enhancement

#3940 Modularized nginx, added gzip, added cache expiration
  Dockerfile
  docker/nginx-seed.conf
  docker/nginx/nginx.conf
  docker/nginx/seed-csp.conf
  docker/nginx/seed-security-headers.conf
  docker/nginx/seed-uwsgi.conf
Labels: Enhancement

#3935 Increase AnalysisMessage.user_message length
  seed/migrations/0190_auto_20230324_1451.py
  seed/models/analysis_messages.py
  seed/static/seed/partials/analyses.html
  seed/static/seed/partials/analysis_runs.html
Labels: Bug

#3944 Fixes Timeline Bugs
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_detail_timeline_controller.js
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/partials/inventory_detail_nav.html
  seed/static/seed/partials/inventory_detail_timeline.html
  seed/static/seed/scss/style.scss
Labels: Bug

#3949 Fix editing a derived column without changing the name
  seed/static/seed/js/controllers/derived_columns_admin_controller.js
  seed/static/seed/js/controllers/derived_columns_editor_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/partials/accounts_nav.html
  seed/static/seed/partials/derived_columns_admin.html
Labels: Bug

#3950 Bump version and update changelog
  CHANGELOG.md
  docs/source/migrations.rst
  package-lock.json
  package.json
Labels: Maintenance, Do not publish
