Repository SEED-platform/seed, pull requests merged in 2023-09, with the labels that each got.

#4012 Add new `create_property` and `update_with_espm` endpoint
  .cspell/custom-dictionary-workspace.txt
  .gitignore
  docs/source/translation.rst
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  lokalise.yml.example
  requirements/base.txt
  seed/building_sync/building_sync.py
  seed/data_importer/models.py
  seed/data_importer/tasks.py
  seed/lib/xml_mapping/mapper.py
  seed/lib/xml_mapping/reader.py
  seed/models/column_mapping_profiles.py
  seed/serializers/properties.py
  seed/static/seed/js/controllers/data_upload_espm_modal_controller.js
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/directives/sdUploader.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/espm_service.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/data_upload_espm_modal.html
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/scss/style.scss
  seed/templates/seed/_scripts.html
  seed/tests/data/mappings/espm-single-mapping.csv
  seed/tests/data/portfolio-manager-single-22482007.xlsx
  seed/tests/test_account_views.py
  seed/tests/test_api_mixins.py
  seed/tests/test_portfoliomanager.py
  seed/tests/test_property_views.py
  seed/tests/util.py
  seed/utils/api_schema.py
  seed/views/v3/analyses.py
  seed/views/v3/columns.py
  seed/views/v3/portfolio_manager.py
  seed/views/v3/properties.py
Labels: Feature

#4223 Fix display name
  seed/static/seed/js/controllers/analysis_run_controller.js
  seed/static/seed/partials/analysis_runs.html
Labels: Bug

#4221 Fix refresh_metadata
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/inventory_list_legacy_controller.js
  seed/static/seed/js/controllers/set_update_to_now_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/inventory_service.js
  seed/static/seed/partials/inventory_list.html
  seed/static/seed/partials/inventory_list_legacy.html
  seed/static/seed/partials/set_update_to_now_modal.html
  seed/tasks.py
  seed/templates/seed/_scripts.html
  seed/tests/test_tax_lot_property.py
  seed/views/v3/tax_lot_properties.py
Labels: Bug

#4225 Remove Beta label from text of analysis button
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
Labels: Enhancement

#4171 Add access level name/ column display name constraints
  seed/lib/superperms/orgs/models.py
  seed/models/columns.py
  seed/tests/test_column_views.py
  seed/tests/test_organization_access_levels.py
  seed/views/v3/columns.py
Labels: Feature, Acct. Hierarchy

#4194 Ah permissions/green assessments view sets
  seed/tests/test_green_assessments.py
  seed/views/v3/green_assessment_properties.py
  seed/views/v3/green_assessment_urls.py
  seed/views/v3/green_assessments.py
Labels: Feature, Acct. Hierarchy

#4196 Ah/disallow nonroot owners
  seed/lib/superperms/orgs/models.py
  seed/tests/test_admin_views.py
  seed/views/v3/organization_users.py
  seed/views/v3/users.py
Labels: Feature, Acct. Hierarchy

#4201 Add permissions to postofficeviewset
  seed/tests/test_postoffice.py
  seed/views/v3/postoffice.py
Labels: Feature, Acct. Hierarchy

#4229 Fix Meters Without `source_id`
  seed/static/seed/js/controllers/inventory_detail_meters_controller.js
Labels: Bug

#4213 Fix performance for fetching analyses and force user email to lowercase
  seed/models/analysis_property_views.py
  seed/views/v3/users.py
Labels: Bug

#4230 Fix loading ALI to be foreground task only
  seed/data_importer/tasks.py
  seed/serializers/properties.py
  seed/tests/test_property_views.py
  seed/views/v3/properties.py
Labels: Bug

#4204 Ah permissions/salesforce
  seed/views/v3/salesforce_mappings.py
Labels: Feature, Acct. Hierarchy

#4224 Ah permissions/analysis view set
  seed/lib/superperms/orgs/decorators.py
  seed/migrations/0206_analysis_access_level_instance.py
  seed/models/analyses.py
  seed/test_helpers/fake.py
  seed/tests/test_analyses_views.py
  seed/tests/test_analysis_messages.py
  seed/views/v3/analyses.py
  seed/views/v3/analysis_messages.py
  seed/views/v3/analysis_views.py
Labels: Feature, Acct. Hierarchy

#4212 Add TaxLotProperty constraints
  seed/models/properties.py
  seed/models/tax_lot_properties.py
  seed/models/tax_lots.py
  seed/test_helpers/fake.py
  seed/tests/test_tax_lot_property.py
  seed/tests/util.py
Labels: Enhancement, Acct. Hierarchy

#4205 Add Permissions to GBRPropertyViewSet
  seed/api/v3/urls.py
  seed/lib/superperms/orgs/decorators.py
  seed/serializers/properties.py
  seed/tests/test_gbr_properties.py
  seed/views/v3/gbr_properties.py
Labels: Feature, Acct. Hierarchy

#4198 Show Analysis `debug_message` If Available
  seed/static/seed/partials/analyses.html
  seed/static/seed/partials/analysis_runs.html
Labels: Enhancement, Bug

#4216 Add permissions to some org endpoints
  seed/lib/superperms/orgs/decorators.py
  seed/tests/test_organization_views.py
  seed/views/v3/organizations.py
Labels: Enhancement, Acct. Hierarchy

#4162 Add permissions to TaxlotViewSet
  seed/test_helpers/fake.py
  seed/tests/test_taxlot_views.py
  seed/tests/util.py
  seed/utils/match.py
  seed/utils/taxlots.py
  seed/views/v3/taxlots.py
Labels: Feature, Acct. Hierarchy

#4060 Use display name in custom reports legend
  seed/models/data_views.py
  seed/static/seed/js/controllers/data_view_controller.js
  seed/tests/test_data_view_views.py
Labels: Enhancement

#4234 Add permissions to Taxlot Properties
  seed/tests/test_tax_lot_property.py
  seed/views/v3/tax_lot_properties.py
Labels: Feature, Acct. Hierarchy

#4227 Allow analysis property view related properties to be null
  seed/migrations/0205_auto_20230913_1417.py
  seed/models/analysis_property_views.py
  seed/static/seed/js/controllers/delete_modal_controller.js
  seed/static/seed/js/services/analyses_service.js
  seed/static/seed/partials/analyses.html
  seed/static/seed/partials/analysis_runs.html
  seed/static/seed/partials/delete_modal.html
  seed/views/v3/analyses.py
Labels: Maintenance, Acct. Hierarchy

#4237 Add more API documentation for meter and meter readings
  .cspell/custom-dictionary-workspace.txt
  seed/static/seed/js/controllers/inventory_detail_meters_controller.js
  seed/utils/api_schema.py
  seed/utils/meters.py
  seed/views/v3/label_inventories.py
  seed/views/v3/meter_readings.py
  seed/views/v3/meters.py
Labels: Enhancement

#3862 Update inventory selection to include current inventory type only
  seed/static/seed/js/controllers/inventory_list_controller.js
Labels: Bug

#3819 Update default meter range selection for BETTER analysis
  seed/analysis_pipelines/better/pipeline.py
  seed/static/seed/js/controllers/inventory_detail_analyses_controller.js
  seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
  seed/static/seed/partials/inventory_detail_analyses_modal.html
Labels: Enhancement

#4217 Delete BuildingFiles and Related Events on PropertyState delete
  seed/migrations/0206_auto_20230908_1319.py
  seed/models/events.py
  seed/models/scenarios.py
Labels: Bug

#4240 Fixed Issues with Scenario/Measure CRUD Operations
  seed/models/property_measures.py
  seed/models/scenarios.py
  seed/tests/test_property_measures.py
  seed/utils/api_schema.py
  seed/views/v3/meters.py
  seed/views/v3/property_measures.py
  seed/views/v3/property_scenarios.py
Labels: Bug

#3837 Add a cycle indicator to the analysis modal and filter analyses for current cycle
  seed/static/seed/js/controllers/analyses_controller.js
  seed/static/seed/js/controllers/analysis_details_controller.js
  seed/static/seed/js/controllers/inventory_detail_analyses_controller.js
  seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/partials/analyses.html
  seed/static/seed/partials/analysis_card.html
  seed/static/seed/partials/analysis_details.html
  seed/static/seed/partials/inventory_detail_analyses.html
  seed/static/seed/partials/inventory_detail_analyses_modal.html
Labels: Enhancement

#4222 Disable ability to remove matching criteria fields once inventory is added
  seed/static/seed/js/controllers/column_settings_controller.js
  seed/static/seed/js/controllers/confirm_column_settings_modal_controller.js
  seed/static/seed/js/services/organization_service.js
  seed/static/seed/partials/column_settings.html
  seed/static/seed/partials/confirm_column_settings_modal.html
  seed/tests/test_account_views.py
  seed/tests/test_organization_views.py
  seed/views/v3/organizations.py
Labels: Maintenance, Acct. Hierarchy

#4241 Add permissions to GeocodeViewSet
  seed/tests/test_geocode_views.py
  seed/views/v3/geocode.py
Labels: Feature, Acct. Hierarchy

#4238 Add Uniformat Table
  .cspell/custom-dictionary-workspace.txt
  custom-dictionary-workspace.txt
  requirements/aws.txt
  requirements/test.txt
  seed/lib/uniformat/uniformat.py
  seed/migrations/0207_uniformat.py
  seed/models/__init__.py
  seed/models/uniformat.py
Labels: Feature

#4250 Fix Meter Overwrites
  seed/analysis_pipelines/eeej.py
  seed/models/meters.py
  seed/serializers/meter_readings.py
  seed/tests/test_meter_views.py
Labels: Impact-1, Bug

#4249 Fix filter group dropdown bugs
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/partials/inventory_list.html
Labels: Filtering, Bug, Clearly Energy

#4215 Add Import Export to Audit Template
  seed/audit_template/audit_template.py
  seed/building_sync/building_sync.py
  seed/building_sync/mappings.py
  seed/lib/superperms/orgs/migrations/0028_organization_audit_template_report_type.py
  seed/lib/superperms/orgs/models.py
  seed/migrations/0208_alter_scenario_event.py
  seed/models/scenarios.py
  seed/static/seed/js/controllers/data_upload_audit_template_modal_controller.js
  seed/static/seed/js/controllers/data_upload_modal_controller.js
  seed/static/seed/js/controllers/export_to_audit_template_modal_controller.js
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/organization_settings_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/audit_template_service.js
  seed/static/seed/partials/data_upload_modal.html
  seed/static/seed/partials/export_to_audit_template_modal.html
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/partials/inventory_list.html
  seed/static/seed/partials/organization_settings.html
  seed/static/seed/scss/style.scss
  seed/templates/seed/_scripts.html
  seed/tests/data/building_sync_xml.txt
  seed/tests/test_account_views.py
  seed/tests/test_audit_template.py
  seed/views/v3/audit_template.py
  seed/views/v3/organizations.py
  seed/views/v3/properties.py
Labels: Feature, Audit Template

#4247 Fix EEEJ analysis errors when there are no lat/long or address
  seed/analysis_pipelines/eeej.py
  seed/analysis_pipelines/tasks.py
  seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
  seed/tests/test_analysis_pipelines.py
Labels: Bug

#4254 Add envvar to specify loading test EEEJ dataset
  config/settings/common.py
  config/settings/test.py
  seed/lib/geospatial/eeej.py
Labels: Enhancement

#4248 Add more Permissions
  seed/tests/test_events.py
  seed/tests/test_property_views.py
  seed/views/v3/events.py
  seed/views/v3/properties.py
Labels: Feature, Acct. Hierarchy

#4246 Add permissions to LabelInventoryViewSet
  seed/tests/test_labels_api_views.py
  seed/views/v3/label_inventories.py
Labels: Feature, Acct. Hierarchy

#4256 Default to excluding Address Line 1 as a matching criteria
  seed/building_sync/tests/data/ex_1_and_buildingsync_ex01_measures.zip
  seed/data_importer/tests/test_match_incoming.py
  seed/static/seed/sample-data/__MACOSX/._seed-sample-data
  seed/static/seed/sample-data/__MACOSX/seed-sample-data/._interval_data-example-pm-monthly-meter-usage.xlsx
  seed/static/seed/sample-data/__MACOSX/seed-sample-data/._interval_data-portfolio-manager-sample.xlsx
  seed/static/seed/sample-data/__MACOSX/seed-sample-data/._simple_data-covered-buildings-sample.csv
  seed/static/seed/sample-data/__MACOSX/seed-sample-data/._simple_data-portfolio-manager-sample.csv
  seed/static/seed/sample-data/seed-sample-data/interval_data-example-pm-monthly-meter-usage.xlsx
  seed/static/seed/sample-data/seed-sample-data/interval_data-portfolio-manager-sample.xlsx
  seed/static/seed/sample-data/seed-sample-data/simple_data-covered-buildings-sample.csv
  seed/static/seed/sample-data/seed-sample-data/simple_data-portfolio-manager-sample.csv
  seed/tests/test_match_existing.py
  seed/tests/test_organization_utils.py
  seed/tests/test_organization_views.py
  seed/tests/test_property_views.py
  seed/tests/test_taxlot_views.py
  seed/utils/organizations.py
Labels: Enhancement

#4259 Bump version
  CHANGELOG.md
  docs/source/migrations.rst
  package-lock.json
  package.json
Labels: Do not publish
