Repository SEED-platform/seed, pull requests merged in 2023-05, with the labels that each got.

#3977 Create access levels
  config/settings/common.py
  requirements/base.txt
  seed/api/v3/urls.py
  seed/lib/superperms/orgs/migrations/0025_auto_20230413_1250.py
  seed/lib/superperms/orgs/models.py
  seed/lib/superperms/tests/test_organization_access_levels.py
  seed/static/seed/js/controllers/organization_access_level_tree_controller.js
  seed/static/seed/js/controllers/organization_add_access_level_instance_modal_controller.js
  seed/static/seed/js/controllers/organization_add_access_level_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/organization_service.js
  seed/static/seed/partials/accounts.html
  seed/static/seed/partials/accounts_nav.html
  seed/static/seed/partials/organization_access_level_tree.html
  seed/static/seed/partials/organization_add_access_level_instance_modal.html
  seed/static/seed/partials/organization_add_access_level_modal.html
  seed/templates/seed/_header.html
  seed/templates/seed/_scripts.html
  seed/tests/test_organization_access_levels.py
  seed/views/v3/access_levels.py
Labels: Feature

#3992 Add salesforce mappings sort and more error checking and messaging
  .pre-commit-config.yaml
  .prettierignore
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/migrations/0192_sf_default_account_fields.py
  seed/models/salesforce_configs.py
  seed/serializers/salesforce_configs.py
  seed/static/seed/js/controllers/organization_settings_controller.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/organization_settings.html
  seed/utils/salesforce.py
  seed/views/v3/salesforce_configs.py
Labels: Enhancement

#3879 Add zoom and panning to insights property page
  seed/static/seed/js/controllers/insights_property_controller.js
Labels: Enhancement

#4007 Remove program overview tabular data
  seed/static/seed/js/controllers/insights_program_controller.js
  seed/static/seed/partials/insights_program.html
Labels: Enhancement

#3994 Save Insight property config locally
  .eslintrc
  seed/static/seed/js/controllers/insights_property_controller.js
  seed/static/seed/partials/insights_property.html
Labels: Enhancement

#4022 adding sf delete_label_on_sync setting
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/migrations/0195_sf_delete_label_checkbox.py
  seed/models/salesforce_configs.py
  seed/serializers/salesforce_configs.py
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/organization_settings.html
  seed/utils/salesforce.py
Labels: Enhancement

#4014 Add in the start and end cycle year to the title
  seed/static/seed/js/controllers/insights_program_controller.js
  seed/static/seed/partials/insights_program.html
Labels: Enhancement

#4028 Bump version and update changelog
  CHANGELOG.md
  docs/source/migrations.rst
  package-lock.json
  package.json
Labels: Maintenance, Do not publish

#4033 Fix duplicate users per organization
  seed/lib/superperms/orgs/migrations/0025_remove_duplicate_users_for_org.py
  seed/lib/superperms/orgs/migrations/0026_organizationuser_unique_user_for_organization.py
  seed/lib/superperms/orgs/models.py
  seed/views/organizations.py
  seed/views/v3/import_files.py
  seed/views/v3/organization_users.py
  seed/views/v3/users.py
Labels: Bug

#4031 Move reports to insights page
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/partials/insights_nav.html
  seed/static/seed/partials/inventory_nav.html
  seed/static/seed/partials/inventory_reports.html
Labels: Enhancement

#4027 Require org id from endpoints with has_perm_class
  seed/lib/superperms/orgs/decorators.py
  seed/tests/test_admin_views.py
  seed/tests/test_audit_template.py
  seed/tests/test_column_views.py
  seed/tests/test_property_views.py
  seed/views/main.py
  seed/views/users.py
  seed/views/v3/measures.py
  seed/views/v3/users.py
Labels: Bug

#4038 remove sync salesforce button due to timeout
  seed/static/seed/partials/organization_settings.html
  seed/utils/salesforce.py
Labels: Bug

#3988 Fix column list profile GET request syntax
  seed/static/seed/js/services/filter_groups_service.js
  seed/static/seed/js/services/inventory_service.js
Labels: Bug

#4011 Direct to property insight on click of program overview column
  seed/static/seed/js/controllers/insights_program_controller.js
Labels: Enhancement

#3990 Improve inventory load times
  seed/models/columns.py
  seed/utils/inventory_filter.py
Labels: Performance

#3987 Updated installation steps
  docs/source/setup_osx.rst
  requirements/base.txt
Labels: Documentation, Maintenance, dependencies

#4059 Pin urllib3
  requirements/test.txt
Labels: Maintenance

#4057 Prevent Automatically Serving Static `index.html` Files
  docker/nginx/nginx.conf
Labels: Bug

#4065 Add Terms of Service
  docker/nginx/nginx.conf
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/landing/models.py
  seed/landing/static/landing/scss/landing.scss
  seed/landing/templates/landing/_browser_supported.html
  seed/landing/templates/landing/_marketing_bullets.html
  seed/landing/templates/landing/home.html
  seed/landing/templates/landing/login.html
  seed/landing/templates/tos/tos_check.html
  seed/landing/tests.py
  seed/landing/urls.py
  seed/landing/views.py
  seed/static/seed/Terms_of_Service.txt
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/about.html
Labels: Feature
