Repository SEED-platform/seed, pull requests merged in 2023-06, with the labels that each got.

#4030 Add ranked sorting to insight property page
  seed/static/seed/js/controllers/insights_property_controller.js
Labels: Enhancement

#4077 Add percentages to program overview
  seed/static/seed/js/controllers/insights_program_controller.js
Labels: Enhancement

#4094 Fix User Creation Bugs
  seed/lib/superperms/orgs/decorators.py
  seed/management/commands/create_default_user.py
  seed/static/seed/js/controllers/admin_controller.js
  seed/views/v3/users.py
Labels: Bug

#4068 Init Accountability Hierarchy
  config/settings/common.py
  requirements/base.txt
  seed/api/v3/urls.py
  seed/lib/superperms/orgs/decorators.py
  seed/lib/superperms/orgs/migrations/0027_auto_20230413_1250.py
  seed/lib/superperms/orgs/models.py
  seed/lib/superperms/tests/test_organization_access_levels.py
  seed/management/commands/make_superuser.py
  seed/migrations/0196_auto_add_props_to_tree.py
  seed/models/properties.py
  seed/models/tax_lots.py
  seed/static/seed/js/controllers/members_controller.js
  seed/static/seed/js/controllers/menu_controller.js
  seed/static/seed/js/controllers/new_member_modal_controller.js
  seed/static/seed/js/controllers/organization_access_level_tree_controller.js
  seed/static/seed/js/controllers/organization_add_access_level_instance_modal_controller.js
  seed/static/seed/js/controllers/organization_add_access_level_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/organization_service.js
  seed/static/seed/js/services/user_service.js
  seed/static/seed/partials/accounts.html
  seed/static/seed/partials/accounts_nav.html
  seed/static/seed/partials/members.html
  seed/static/seed/partials/new_member_modal.html
  seed/static/seed/partials/organization_access_level_tree.html
  seed/static/seed/partials/organization_add_access_level_instance_modal.html
  seed/static/seed/partials/organization_add_access_level_modal.html
  seed/static/seed/tests/members_controller.spec.js
  seed/static/seed/tests/new_member_modal_controller.spec.js
  seed/templates/seed/_header.html
  seed/templates/seed/_scripts.html
  seed/templates/seed/base.html
  seed/tests/test_account_views.py
  seed/tests/test_admin_views.py
  seed/tests/test_api.py
  seed/tests/test_media.py
  seed/tests/test_organization_access_levels.py
  seed/tests/test_permissions.py
  seed/tests/test_scenarios.py
  seed/tests/test_sharing.py
  seed/tests/test_views.py
  seed/utils/inventory_filter.py
  seed/utils/organizations.py
  seed/views/main.py
  seed/views/organizations.py
  seed/views/users.py
  seed/views/v3/access_levels.py
  seed/views/v3/organization_users.py
  seed/views/v3/organizations.py
  seed/views/v3/users.py
Labels: Feature, Acct. Hierarchy

#4085 Fix categorical data on reports scatter plot
  seed/static/seed/js/controllers/inventory_reports_controller.js
Labels: Bug

#4072 Add matching criteria to report export
  seed/tests/test_reports.py
  seed/views/v3/organizations.py
Labels: Enhancement

#4109 remove OEP
  .dockerignore
  deploy.sh
  docker-compose.build.yml
  docker-compose.local.yml
  docker-compose.yml
  docs/source/docker.rst
  docs/source/migrations.rst
  seed/docs/faq/features/get-general-info.md
  seed/docs/faq/industry involvement/plugins.md
  seed/serializers/labels.py
  seed/tasks.py
Labels: Maintenance

#4096 Fix ESPM Source Types
  seed/data_importer/migrations/0017_pm_source_type.py
  seed/data_importer/tasks.py
  seed/data_importer/tests/integration/test_data_import.py
  seed/data_importer/tests/test_match_incoming.py
  seed/data_importer/views.py
  seed/migrations/0196_alter_source_types.py
  seed/migrations/0197_pm_source_type.py
  seed/models/column_mappings.py
  seed/models/models.py
  seed/models/properties.py
  seed/tests/test_greenbutton_import.py
  seed/tests/test_import_file_views.py
  seed/tests/test_meter_usage_import.py
  seed/tests/test_property_views.py
  seed/tests/test_tasks.py
  seed/tests/util.py
  seed/views/v3/import_files.py
  seed/views/v3/organizations.py
  seed/views/v3/uploads.py
Labels: Bug

#4099 Add Permisions for DataLoggerViewSet
  seed/lib/superperms/orgs/decorators.py
  seed/tests/test_property_views.py
  seed/views/v3/data_logger.py
Labels: Feature, Acct. Hierarchy

#4116 Add AH Permissions to MeterViewSet
  seed/tests/test_meter_views.py
  seed/tests/test_property_views.py
  seed/views/v3/meters.py
Labels: Enhancement, Acct. Hierarchy

#4115 Add AH Permissions to Scenarios
  seed/tests/test_scenarios.py
  seed/views/v3/property_scenarios.py
Labels: Enhancement

#4061 Import ah from file
  seed/data_importer/access_level_instances_parser.py
  seed/data_importer/tasks.py
  seed/lib/superperms/orgs/models.py
  seed/static/seed/js/controllers/data_upload_modal_controller.js
  seed/static/seed/js/controllers/organization_access_level_tree_controller.js
  seed/static/seed/js/controllers/organization_add_access_level_instance_modal_controller.js
  seed/static/seed/js/controllers/organization_add_access_level_modal_controller.js
  seed/static/seed/js/controllers/organization_edit_access_level_instance_modal_controller.js
  seed/static/seed/js/directives/sdUploader.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/organization_service.js
  seed/static/seed/js/services/uploader_service.js
  seed/static/seed/partials/access_level_instances_import_messages.html
  seed/static/seed/partials/data_upload_modal.html
  seed/static/seed/partials/data_upload_modal_progress.html
  seed/static/seed/partials/organization_access_level_tree.html
  seed/static/seed/partials/organization_add_access_level_instance_modal.html
  seed/static/seed/partials/organization_add_access_level_modal.html
  seed/static/seed/partials/organization_edit_access_level_instance_modal.html
  seed/static/seed/scss/style.scss
  seed/templates/seed/_scripts.html
  seed/tests/data/access-level-instances.xlsx
  seed/tests/data/access-levels-wrong1.xlsx
  seed/tests/data/access-levels-wrong2.xlsx
  seed/tests/data/access-levels-wrong3.xlsx
  seed/tests/test_organization_access_levels.py
  seed/views/v3/access_levels.py
Labels: Feature, Acct. Hierarchy

#4118 Add permissions to CycleViewSet
  seed/tests/test_cycles.py
  seed/views/v3/cycles.py
Labels: Enhancement, Acct. Hierarchy

#4066 Fix Download URLs
  seed/static/seed/js/controllers/dataset_detail_controller.js
  seed/static/seed/partials/dataset_detail.html
Labels: Bug
