Repository SEED-platform/seed, pull requests merged in 2023-01, with the labels that each got.

#3733 Fix filter on nulls and empty strings
  seed/utils/search.py
Labels: Bug

#3729 Add the @has_perm_class permission to program metric api endpoints
  seed/static/seed/js/controllers/program_setup_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/partials/accounts.html
  seed/static/seed/partials/accounts_nav.html
  seed/static/seed/partials/program_setup.html
  seed/templates/seed/_header.html
  seed/views/v3/compliance_metrics.py
Labels: Bug

#3738 fix meter service route for units in organization settings
  seed/static/seed/js/services/meters_service.js
Labels: Bug

#3740 Fix custom report legend sort for chrome
  seed/static/seed/js/controllers/data_view_controller.js
Labels: Bug

#3748 Sort column mappings in profile before export
  seed/views/v3/column_mapping_profiles.py
Labels: Bug

#3747 Remove all extra spaces in headers from XLSX files
  seed/data_importer/meters_parser.py
  seed/data_importer/tests/data/example-pm-data-request-with-meters.xlsx
  seed/data_importer/tests/test_meters_parser.py
  seed/lib/mcm/reader.py
Labels: Enhancement

#3728 Update derived column migration to prevent conflicting column names and prevent duplicate column names
  seed/migrations/0170_column_derived_column.py
  seed/models/derived_columns.py
  seed/serializers/derived_columns.py
  seed/static/seed/js/controllers/derived_columns_editor_controller.js
  seed/static/seed/partials/derived_columns_editor.html
  seed/test_helpers/fake.py
  seed/tests/test_derived_columns.py
Labels: Bug

#3745 Fixed issue with overlapping meter readings with new ESPM format
  seed/data_importer/meters_parser.py
  seed/data_importer/tests/data/example-pm-data-request-with-meters-new-format.xlsx
  seed/data_importer/tests/data/example-pm-data-request-with-meters.xlsx
  seed/data_importer/tests/test_meters_parser.py
  seed/lib/mcm/reader.py
  seed/models/meters.py
Labels: Bug

#3735 Show portfolio manager errors
  seed/static/seed/js/controllers/data_upload_modal_controller.js
  seed/static/seed/partials/data_upload_modal.html
Labels: Enhancement

#3726 Allow users to hide property insight dataset
  seed/static/seed/js/controllers/insights_property_controller.js
  seed/static/seed/partials/insights_property.html
  seed/static/seed/scss/style.scss
Labels: Enhancement

#3781 remove references to prod server, as needed
  CHANGELOG.md
  bin/drop_create_db.sh
  docs/source/developer_resources.rst
  docs/source/setup_osx.rst
  seed/docs/faq/industry involvement/plugins.md
  seed/tests/api/test_seed_host_api.py
Labels: Do not publish

#3782 Update help text
  docs/source/help.rst
Labels: Do not publish

#3765 Fix filtering on "" and !"" for all data types
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/filters/tolerantNumber.js
  seed/static/seed/js/seed.js
  seed/templates/seed/_scripts.html
  seed/tests/test_search.py
  seed/utils/search.py
Labels: Bug

#3789 Fix bug where compliance calculations were not being cast to the right data types
  .pre-commit-config.yaml
  seed/migrations/0170_column_derived_column.py
  seed/migrations/0180_remove_property_campus.py
  seed/models/columns.py
  seed/models/compliance_metrics.py
  seed/models/properties.py
  seed/tests/test_columns.py
  seed/tests/test_search.py
  seed/utils/search.py
Labels: Bug

#3790 Mark icebox-labeled issues as stale after 180 days
  .github/workflows/pr-labels.yml
  .github/workflows/stale-ice-box.yml
  .github/workflows/stale.yml
Labels: Do not publish

#3793 Prep release 2.17.1
  .github/workflows/pr-labels.yml
  CHANGELOG.md
  docs/source/migrations.rst
  npm-shrinkwrap.json
  package.json
Labels: Do not publish

#3803 Fix 500 on data view evaluate when extra data is not present
  seed/models/data_views.py
Labels: Bug

#3791 Catch create column error correctly
  seed/static/seed/js/controllers/create_column_modal_controller.js
Labels: Bug

#3811 Show all navs in org
  seed/static/seed/js/seed.js
Labels: Bug
