Repository SEED-platform/seed, pull requests merged in 2023-10, with the labels that each got.

#4263 Fix the items in the 2.20.0 changelog
  CHANGELOG.md
Labels: Do not publish

#4265 ArcGIS CSP rule
  docker/nginx/seed-csp.conf
Labels: Bug

#4170 Ah/import frontend
  seed/static/seed/js/controllers/data_upload_modal_controller.js
  seed/static/seed/js/controllers/mapping_controller.js
  seed/static/seed/partials/data_upload_modal.html
  seed/tests/test_account_views.py
  seed/views/v3/import_files.py
  seed/views/v3/organizations.py
Labels: Feature, Acct. Hierarchy

#4264 Add documentation for cleaning up conflicting column names during migration
  docs/source/migrations.rst
Labels: Documentation

#4268 Update changelog for 2.20.0
  CHANGELOG.md
Labels: Do not publish

#4270 Fix edge case for map label filtering
  seed/static/seed/js/controllers/inventory_map_controller.js
Labels: Bug

#4272 Update changelog
  CHANGELOG.md
Labels: Do not publish

#4273 Release 2.20.0 (again)
  CHANGELOG.md
  docker/nginx/seed-csp.conf
  docs/source/migrations.rst
  seed/static/seed/js/controllers/inventory_map_controller.js
Labels: Do not publish

#4258 Update Redis config to support encryption in transit with AWS ElastiCache
  .cspell/custom-dictionary-workspace.txt
  config/settings/docker.py
  config/settings/docker_dev.py
  requirements/aws.txt
Labels: Enhancement

#4235 Fix user creation bug
  seed/static/seed/js/controllers/admin_controller.js
  seed/static/seed/js/controllers/new_member_modal_controller.js
  seed/static/seed/partials/admin.html
  seed/static/seed/partials/new_member_modal.html
  seed/static/seed/tests/new_member_modal_controller.spec.js
  seed/tests/test_admin_views.py
  seed/views/v3/users.py
Labels: Feature, Bug, Acct. Hierarchy

#4276 Fix mapping of BETTER's measures with empty strings to false
  seed/analysis_pipelines/better/pipeline.py
Labels: Bug

#4277 move cspell config to json and to the root
  .cspell.json
  .cspell/custom-dictionary-workspace.txt
  docs/source/conf.py
Labels: Do not publish

#4280 Decrease BETTER polling rate 5x, increase timeout 5x
  seed/analysis_pipelines/better/client.py
Labels: Enhancement

#4281 Enable natural sorting of Inventory List columns
  seed/migrations/0210_natural_sort.py
  seed/models/properties.py
  seed/models/tax_lots.py
  seed/tests/test_search.py
  seed/utils/search.py
Labels: Bug

#4283 Build docker container for accountability branch
  .github/workflows/publish.yml
Labels: Do not publish

#4287 Handle ambiguous timestamps
  seed/data_importer/meters_parser.py
Labels: Bug

#4296 Increase ESPM max timeout
  seed/views/v3/portfolio_manager.py
Labels: Enhancement

#4291 Fix cycle deletion modal
  seed/static/seed/js/controllers/cycle_admin_controller.js
Labels: Bug

#4294 Handle nonexistent timestamps
  seed/data_importer/meters_parser.py
  seed/data_importer/tests/test_meters_parser.py
Labels: Bug

#4288 Feature to enable Redis for ElastiCache
  config/settings/docker.py
Labels: Feature

#4300 Update list of BETTER's measures returned
  .cspell.json
  seed/analysis_pipelines/better/pipeline.py
Labels: Enhancement

#4282 Add failing logic to AT export if AT credentials are invalid
  docker-compose.dev.yml
  seed/audit_template/audit_template.py
  seed/static/seed/js/controllers/export_to_audit_template_modal_controller.js
  seed/static/seed/partials/export_to_audit_template_modal.html
  seed/tests/test_audit_template.py
  seed/views/v3/audit_template.py
Labels: Bug

#4304 Add analysis description translations
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
Labels: Bug

#4303 Fix tests
  seed/tests/test_account_views.py
  seed/tests/test_data_view_views.py
  seed/tests/test_meter_views.py
  seed/tests/test_property_views.py
  seed/views/v3/analyses.py
Labels: Bug, Acct. Hierarchy

#4364 Fix showing derived column values on the inventory list page
  seed/static/seed/js/controllers/inventory_list_controller.js
Labels: Bug

#4371 Health check endpoint
  config/urls.py
  seed/views/main.py
Labels: Feature

#4284 Add option to delete alis
  seed/static/seed/js/controllers/organization_access_level_tree_controller.js
  seed/static/seed/js/controllers/organization_add_access_level_modal_controller.js
  seed/static/seed/js/controllers/organization_delete_access_level_instance_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/organization_service.js
  seed/static/seed/partials/organization_access_level_tree.html
  seed/static/seed/partials/organization_add_access_level_modal.html
  seed/static/seed/partials/organization_delete_access_level_instance_modal.html
  seed/templates/seed/_scripts.html
  seed/tests/test_organization_access_levels.py
  seed/views/v3/access_levels.py
Labels: Feature, Acct. Hierarchy

#4289 update modal step ID
  seed/static/seed/js/controllers/organization_access_level_tree_controller.js
Labels: Bug, Acct. Hierarchy

#4373 Updated developer resources documentation
  docs/source/developer_resources.rst
Labels: Documentation

#4297 Permission UploadViewSet
  seed/lib/superperms/orgs/decorators.py
  seed/tests/test_portfoliomanager.py
  seed/views/v3/uploads.py
Labels: Feature, Acct. Hierarchy

#4298 Add Permissions to TaxlotViewViewSet
  seed/tests/test_taxlot_views_viewset.py
  seed/views/v3/taxlot_views.py
Labels: Feature, Acct. Hierarchy
