Repository SEED-platform/seed, pull requests merged in 2023-07, with the labels that each got.

#4119 Add Permissions to ColumnViewSet
  seed/tests/test_column_views.py
  seed/views/v3/columns.py
Labels: Enhancement, Acct. Hierarchy

#4067 Accountability Hierarchy Page Formatting
  seed/static/seed/js/controllers/organization_access_level_tree_controller.js
  seed/static/seed/partials/organization_access_level_tree.html
  seed/static/seed/scss/style.scss
Labels: Feature, Acct. Hierarchy

#4073 Multiple cycle upload
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  script/get_angular_translations.sh
  script/get_python_translations.sh
  seed/data_importer/match.py
  seed/data_importer/migrations/0018_importfile_multiple_cycle_upload.py
  seed/data_importer/models.py
  seed/data_importer/tasks.py
  seed/data_importer/tests/data/MultiCycle_Test.xlsx
  seed/data_importer/tests/integration/test_data_import.py
  seed/data_importer/tests/integration/test_demo_v2.py
  seed/data_importer/tests/integration/test_footprints_import.py
  seed/data_importer/tests/test_match_incoming.py
  seed/management/commands/create_and_load_sample_data.py
  seed/migrations/0198_auto_20230703_0828.py
  seed/models/cycles.py
  seed/static/seed/js/controllers/cycle_admin_controller.js
  seed/static/seed/js/controllers/data_upload_modal_controller.js
  seed/static/seed/js/controllers/mapping_controller.js
  seed/static/seed/js/services/uploader_service.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/cycle_admin.html
  seed/static/seed/partials/data_upload_modal.html
  seed/static/seed/partials/data_upload_modal_progress.html
  seed/static/seed/tests/data_quality_modal_controller.spec.js
  seed/static/seed/tests/data_upload_modal_controller.spec.js
  seed/static/seed/tests/dataset_detail_controller.spec.js
  seed/static/seed/tests/property_detail_controller.spec.js
  seed/static/seed/tests/taxlot_detail_controller.spec.js
  seed/tests/api/test_modules.py
  seed/tests/data/2019-2020_Multiple Cycle Taxlots.xlsx
  seed/tests/data/2019-2020_Multiple Cycle Year only.xlsx
  seed/tests/data/Sample_MultipleCycles.xlsx
  seed/tests/data/bps/BPS_Sample_AT_21381.xml
  seed/tests/test_api.py
  seed/tests/util.py
  seed/views/v3/import_files.py
Labels: Feature

#4020 Store additional geocoding results
  seed/models/columns.py
  seed/utils/geocode.py
Labels: Feature

#4126 Ah permissions/import file view set
  seed/data_importer/match.py
  seed/data_importer/migrations/0017_importrecord_access_level_instance.py
  seed/data_importer/models.py
  seed/data_importer/tasks.py
  seed/data_importer/tests/integration/test_data_import.py
  seed/data_importer/tests/integration/test_demo_v2.py
  seed/data_importer/tests/integration/test_equivalence_partioner_with_file.py
  seed/data_importer/tests/integration/test_footprints_import.py
  seed/data_importer/tests/integration/test_merge_duplicate_rows.py
  seed/data_importer/tests/test_AH_import.py
  seed/data_importer/tests/test_link_incoming.py
  seed/data_importer/tests/test_mapping.py
  seed/data_importer/tests/test_match_incoming.py
  seed/lib/merging/merging.py
  seed/lib/superperms/orgs/decorators.py
  seed/migrations/0197_auto_20230623_1556.py
  seed/models/building_file.py
  seed/models/columns.py
  seed/models/properties.py
  seed/models/tax_lots.py
  seed/tests/test_account_views.py
  seed/tests/test_greenbutton_import.py
  seed/tests/test_import_file_views.py
  seed/tests/test_match_existing.py
  seed/tests/test_media.py
  seed/tests/test_meter_usage_import.py
  seed/tests/test_organization_views.py
  seed/tests/test_property_views.py
  seed/tests/test_tasks.py
  seed/tests/test_taxlot_views.py
  seed/tests/test_views.py
  seed/tests/util.py
  seed/views/datasets.py
  seed/views/v3/datasets.py
  seed/views/v3/import_files.py
  seed/views/v3/organizations.py
Labels: Feature, Acct. Hierarchy

#4131 Add permissions to DataViewViewSet
  seed/models/data_views.py
  seed/tests/test_data_view_views.py
  seed/views/v3/data_views.py
Labels: Feature, Acct. Hierarchy

#4138 Ah bug fixes
  seed/static/seed/js/controllers/menu_controller.js
  seed/static/seed/js/controllers/new_member_modal_controller.js
  seed/static/seed/partials/new_member_modal.html
  seed/templates/seed/_header.html
  seed/tests/test_account_views.py
  seed/views/main.py
Labels: Bug, Acct. Hierarchy

#4134 Add aln contraints
  seed/lib/superperms/orgs/models.py
  seed/models/columns.py
  seed/tests/test_columns.py
  seed/tests/test_organization_access_levels.py
  seed/utils/organizations.py
  seed/views/v3/access_levels.py
Labels: Feature, Acct. Hierarchy

#4139 Use iterator() when rehashing to save memory
  seed/migrations/0200_rehash.py
Labels: Bug

#4140 Add permissions to DerivedColumnViewSet
  seed/tests/test_derived_columns.py
  seed/views/v3/derived_columns.py
Labels: Feature, Acct. Hierarchy

#4141 Fix ali rename
  seed/lib/superperms/orgs/models.py
Labels: Bug, Acct. Hierarchy

#4133 Add access level instance visualisation to inventory list and detail
  seed/models/data_views.py
  seed/models/tax_lot_properties.py
  seed/serializers/access_level_instances.py
  seed/serializers/properties.py
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/partials/inventory_list.html
  seed/static/seed/scss/style.scss
  seed/tests/test_search.py
  seed/utils/inventory_filter.py
  seed/utils/properties.py
  seed/utils/search.py
Labels: Feature, Acct. Hierarchy

#4149 Merge sphinx spelling list with VSCode's Code Spelling version
  .cspell/custom-dictionary-workspace.txt
  CHANGELOG.md
  LICENSE.md
  custom-dictionary-workspace.txt
  docs/source/conf.py
  docs/source/developer_resources.rst
  docs/source/kubernetes_deployment.rst
  docs/source/linux.rst
  docs/source/matching.rst
  docs/source/migrations.rst
  docs/source/setup_docker.rst
  docs/source/translation.rst
  requirements/base.txt
  seed/analysis_pipelines/pipeline.py
  seed/analysis_pipelines/utils.py
  seed/building_sync/mappings.py
  seed/data_importer/tasks.py
  seed/models/analyses.py
  seed/models/analysis_input_files.py
  seed/ogbs/flippers.py
  seed/serializers/pint.py
  seed/static/seed/js/controllers/derived_columns_editor_controller.js
  seed/static/seed/js/services/analyses_service.js
  seed/tests/test_derived_columns.py
  seed/tests/test_permissions.py
  seed/tests/test_property_measures.py
  seed/utils/geocode.py
  seed/utils/search.py
  seed/views/v3/data_quality_check_rules.py
  seed/views/v3/data_quality_checks.py
  seed/views/v3/organization_users.py
  seed/views/v3/organizations.py
Labels: Documentation

#4151 Constrain uniqueness of column name and move geocoding column creation
  .cspell/custom-dictionary-workspace.txt
  .github/workflows/ci.yml
  Dockerfile
  Dockerfile-dev
  requirements/base.txt
  seed/data_importer/tasks.py
  seed/data_importer/tests/test_mapping.py
  seed/migrations/0203_column_unique_column_name.py
  seed/models/columns.py
  seed/tests/test_address_normalization.py
  seed/tests/test_meter_views.py
  seed/tests/test_salesforce_views.py
  seed/utils/geocode.py
  seed/utils/salesforce.py
  seed/views/building_file.py
  seed/views/tax_lot_properties.py
  seed/views/v3/building_files.py
Labels: Bug

#4127 Add permissions to ColumnMappingProfileViewSet
  seed/tests/test_column_mapping_profiles_views.py
  seed/views/v3/column_mapping_profiles.py
Labels: Feature, Acct. Hierarchy

#4158 Add ESPM download for single property (via API)
  .cspell/custom-dictionary-workspace.txt
  .gitignore
  seed/lib/xml_mapping/mapper.py
  seed/tests/test_portfoliomanager.py
  seed/views/v3/analyses.py
  seed/views/v3/portfolio_manager.py
Labels: Feature

#4165 Lock `google-chrome` to v114
  .github/workflows/ci.yml
Labels: Maintenance
