Repository SEED-platform/seed, pull requests merged in 2024-11, with the labels that each got.

#4868 Updates to meter connection modal
  seed/api/v3/urls.py
  seed/migrations/0236_auto_20241030_1434.py
  seed/models/meters.py
  seed/models/systems.py
  seed/serializers/inventory_groups.py
  seed/serializers/meters.py
  seed/static/seed/js/controllers/inventory_detail_meters_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_dashboard_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_meters_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_systems_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/inventory_map_controller.js
  seed/static/seed/js/controllers/meter_deletion_modal_controller.js
  seed/static/seed/js/controllers/meter_edit_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/inventory_group_service.js
  seed/static/seed/js/services/meter_service.js
  seed/static/seed/partials/inventory_group_detail_dashboard.html
  seed/static/seed/partials/inventory_group_detail_meters.html
  seed/static/seed/partials/inventory_group_detail_systems.html
  seed/static/seed/partials/inventory_list.html
  seed/static/seed/partials/inventory_map.html
  seed/static/seed/partials/meter_edit_modal.html
  seed/static/seed/scss/style.scss
  seed/templates/seed/_scripts.html
  seed/tests/test_inventory_groups.py
  seed/tests/test_property_views.py
  seed/tests/test_systems.py
  seed/utils/meters.py
  seed/views/v3/inventory_groups.py
  seed/views/v3/meters.py
Labels: Feature

#4869 Add export charts to default reports
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/static/seed/partials/inventory_reports.html
Labels: Feature

#4866 Move show populated to backend
  seed/models/columns.py
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/show_populated_columns_modal_controller.js
  seed/static/seed/js/services/inventory_service.js
  seed/static/seed/partials/show_populated_columns_modal.html
  seed/tests/test_column_list_profiles_views.py
  seed/views/v3/analyses.py
  seed/views/v3/column_list_profiles.py
Labels: Enhancement

#4452 Fix: Use old cycles during unmerge
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.mo
  locale/es/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/es.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/notes.html
  seed/tests/test_property_views.py
  seed/tests/test_taxlot_views.py
  seed/views/v3/properties.py
  seed/views/v3/taxlots.py
Labels: Bug

#4825 Add progress bar to derived data update
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.mo
  locale/es/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/update_derived_data_modal_controller.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/es.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/unmerge_modal.html
  seed/static/seed/partials/update_derived_data_modal.html
  seed/tasks.py
  seed/views/v3/tax_lot_properties.py
Labels: Feature

#4878 update aggregation table
  seed/static/seed/partials/inventory_reports.html
  seed/static/seed/scss/style.scss
  seed/views/v3/organizations.py
Labels: Enhancement

#4882 Display current access level instance names in default reports
  seed/static/seed/js/controllers/inventory_reports_controller.js
Labels: Bug

#4883 Include derived columns in y axis for default reports
  seed/static/seed/js/controllers/organization_settings_controller.js
  seed/views/v3/organizations.py
Labels: Bug

#4884 Change cts export column name
  seed/views/v3/properties.py
Labels: Bug

#4888 Add derived columns to program setup
  seed/models/compliance_metrics.py
  seed/static/seed/js/controllers/program_setup_controller.js
Labels: Enhancement

#4879 Systems and services improvements
  seed/migrations/0237_auto_20241106_1339.py
  seed/models/meters.py
  seed/models/systems.py
  seed/serializers/meters.py
  seed/serializers/pint.py
  seed/serializers/systems.py
  seed/static/seed/js/controllers/inventory_detail_meters_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_meters_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_systems_controller.js
  seed/static/seed/js/controllers/meter_edit_modal_controller.js
  seed/static/seed/js/controllers/system_modal_controller.js
  seed/static/seed/js/controllers/update_inventory_groups_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/partials/inventory_list.html
  seed/static/seed/partials/meter_edit_modal.html
  seed/static/seed/partials/service_modal.html
  seed/static/seed/partials/services_table.html
  seed/static/seed/partials/system_modal.html
  seed/static/seed/partials/systems_table.html
  seed/static/seed/partials/update_inventory_groups_modal.html
  seed/static/seed/scss/style.scss
  seed/test_helpers/fake.py
  seed/tests/test_inventory_groups.py
  seed/tests/test_meter_views.py
  seed/tests/test_property_views.py
  seed/tests/test_systems.py
  seed/utils/meters.py
  seed/views/v3/inventory_groups.py
  seed/views/v3/systems.py
Labels: Bug

#4887 Fix Default Reports and Analyses
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.mo
  locale/es/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/analysis_pipelines/element_statistics.py
  seed/analysis_pipelines/upgrade_recommendation.py
  seed/models/analyses.py
  seed/models/filter_group.py
  seed/static/seed/js/controllers/inventory_detail_analyses_controller.js
  seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/es.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/partials/inventory_detail_analyses_modal.html
  seed/static/seed/scss/style.scss
  seed/views/v3/organizations.py
Labels: Enhancement, Bug
