Repository SEED-platform/seed, pull requests merged in 2024-01, with the labels that each got.

#4445 Fix ah import messages
  seed/data_importer/tasks.py
Labels: Enhancement, Acct. Hierarchy

#4459 Bug multi cycle test new year update
  seed/data_importer/tests/test_match_incoming.py
Labels: Bug

#4457 Fix Tests
  seed/tests/test_organization_views.py
Labels: Bug

#4461 Fix and optimize sensors
  seed/static/seed/partials/sensors_upload_modal.html
  seed/utils/sensors.py
Labels: Bug

#4455 Fix column names errors
  seed/lib/superperms/orgs/models.py
Labels: Bug

#4473 Restore column filters when unpinning
  seed/static/seed/js/controllers/inventory_list_controller.js
  vendors/package-lock.json
  vendors/package.json
Labels: Bug

#4470 Update copyright to 2024
  LICENSE.md
  docs/source/conf.py
Labels: Maintenance, Do not publish

#4465 Fixes text alignment following FontAwesome changes
  seed/static/seed/scss/style.scss
Labels: Enhancement

#4464 Sensor reading performance improvement
  seed/utils/sensors.py
Labels: Enhancement

#4476 Fix importing diesel meter readings
  seed/data_importer/meters_parser.py
Labels: Bug

#4467 Add bulk meter reading error handling for duplicate date-pairs
  seed/serializers/meter_readings.py
  seed/tests/test_meter_views.py
Labels: Bug

#4469 Retrieve all map data at once
  seed/static/seed/js/controllers/inventory_map_controller.js
Labels: Enhancement

#4472 Change unique name contraint on Derived column so it s within inventory type
  seed/migrations/0211_auto_20240109_1348.py
  seed/models/derived_columns.py
Labels: Enhancement

#4471 Allow omitted fields on the mapping page to be unfilled
  seed/static/seed/js/controllers/mapping_controller.js
Labels: Bug

#4485 Update developer documentation dependencies
  .cspell.json
  .gitignore
  bin/protractor_start_server.sh
  docs/source/conf.py
  docs/source/docker.rst
  docs/source/kubernetes_deployment.rst
  docs/source/migrations.rst
  docs/source/modules/seed.rst
  docs/source/modules/seed.utils.rst
  requirements/test.txt
  tox.ini
Labels: Documentation

#4477 Add JSON response to GET Audit Template submission
  seed/audit_template/audit_template.py
  seed/views/v3/audit_template.py
Labels: Enhancement

#4486 UX updates - access tree view updates
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/static/seed/images/ali-tree-example-lg.png
  seed/static/seed/js/controllers/organization_access_level_tree_controller.js
  seed/static/seed/js/controllers/organization_delete_access_level_instance_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/access_level_instances_import_messages.html
  seed/static/seed/partials/data_upload_modal.html
  seed/static/seed/partials/organization_access_level_tree.html
  seed/static/seed/partials/organization_add_access_level_instance_modal.html
  seed/static/seed/partials/organization_add_access_level_modal.html
  seed/static/seed/partials/organization_delete_access_level_instance_modal.html
  seed/static/seed/partials/organization_edit_access_level_instance_modal.html
  seed/static/seed/scss/style.scss
  seed/templates/seed/_header.html
Labels: Enhancement

#4489 Update ALI table on inventory details page
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/scss/style.scss
Labels: Bug, Acct. Hierarchy

#4458 Show spinner on label creation
  seed/static/seed/js/controllers/update_item_labels_modal_controller.js
  seed/static/seed/partials/update_item_labels_modal.html
Labels: Bug, 2024 Q2 Bug Fixes

#4492 Enable force ali delete
  seed/static/seed/partials/organization_delete_access_level_instance_modal.html
  seed/static/seed/scss/style.scss
Labels: Bug, Acct. Hierarchy

#4475 Catch invalid organization id preventing 500s
  seed/lib/superperms/orgs/permissions.py
  seed/tests/test_permissions.py
  seed/tests/test_views.py
Labels: Bug

#4292 Delete PropertyStateViewSet
  seed/api/v3/urls.py
  seed/views/v3/property_states.py
Labels: Feature, Acct. Hierarchy

#4478 Fix inventory list timing console errors
  seed/static/seed/js/controllers/inventory_list_controller.js
Labels: Bug

#4480 Fix inventory list double refresh on load
  seed/static/seed/js/controllers/inventory_list_controller.js
Labels: Bug

#4493 AH - update dialog text on Upload ALIs modal and collapse help section by default
  seed/static/seed/js/controllers/organization_access_level_tree_controller.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/data_upload_modal_progress.html
  seed/static/seed/partials/organization_access_level_tree.html
Labels: Enhancement

#4462 Apply GHG and GHGI unit versions to canonical columns
  seed/lib/superperms/orgs/migrations/0029_auto_20240105_1257.py
  seed/lib/superperms/orgs/models.py
  seed/static/seed/js/controllers/organization_settings_controller.js
  seed/static/seed/partials/organization_settings.html
  seed/tests/test_account_views.py
  seed/views/v3/organizations.py
Labels: Bug

#4497 Fix inventory loading if no previous sort settings exist in localStorage
  seed/static/seed/js/controllers/inventory_list_controller.js
Labels: Bug

#4501 AH UI Fixes for access level modals
  seed/static/seed/js/controllers/organization_add_access_level_instance_modal_controller.js
  seed/static/seed/partials/accounts.html
  seed/static/seed/partials/accounts_nav.html
  seed/static/seed/partials/data_upload_modal.html
  seed/static/seed/partials/data_upload_modal_progress.html
  seed/static/seed/partials/organization_add_access_level_instance_modal.html
  seed/templates/seed/_header.html
Labels: Bug, Acct. Hierarchy

#4505 fix simple modal service
  seed/static/seed/js/services/simple_modal_service.js
Labels: Bug

#4440 Add Cross Cycle Tabular View for Portfolio Summary Goals
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/api/v3/urls.py
  seed/lib/superperms/orgs/decorators.py
  seed/migrations/0213_goal.py
  seed/models/__init__.py
  seed/models/goals.py
  seed/serializers/goals.py
  seed/static/seed/js/controllers/goal_editor_modal_controller.js
  seed/static/seed/js/controllers/portfolio_summary_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/goal_service.js
  seed/static/seed/js/services/inventory_service.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/goal_editor_modal.html
  seed/static/seed/partials/insights_nav.html
  seed/static/seed/partials/portfolio_summary.html
  seed/static/seed/scss/style.scss
  seed/templates/seed/_scripts.html
  seed/tests/test_goals.py
  seed/utils/goals.py
  seed/utils/inventory_filter.py
  seed/utils/properties.py
  seed/views/v3/goals.py
  seed/views/v3/properties.py
Labels: Feature

#4484 Support unicode characters by replacing unidecode with new normalize method
  .cspell.json
  requirements/base.txt
  seed/data_importer/tasks.py
  seed/data_importer/tests/data/example-data-properties-2-invalid-footprints.xlsx
  seed/data_importer/tests/data/example-data-properties-small-changes.xlsx
  seed/data_importer/tests/data/example-data-properties-unicode.xlsx
  seed/data_importer/tests/data/example-data-properties.xlsx
  seed/data_importer/tests/integration/test_merge_duplicate_rows.py
  seed/data_importer/tests/test_mapping.py
  seed/data_importer/tests/test_match_unicode.py
  seed/data_importer/tests/util.py
  seed/lib/mappings/mapper.py
  seed/lib/mcm/cleaners.py
  seed/lib/mcm/reader.py
  seed/views/v3/data_quality_checks.py
Labels: Feature

#4510 AH - Fix label creation UI
  seed/static/seed/js/controllers/update_item_labels_modal_controller.js
  seed/static/seed/js/services/simple_modal_service.js
Labels: Bug
