Repository SEED-platform/seed, pull requests merged in 2024-09, with the labels that each got.

#4770 Adds developer logs to AT workflow
  seed/audit_template/audit_template.py
Labels: Bug

#4767 Add Number of D.D.C Control Panels to Element Analysis
  seed/analysis_pipelines/element_statistics.py
Labels: Enhancement

#4762 Improve handling of failed ESPM imports
  seed/static/seed/js/controllers/data_upload_modal_controller.js
  seed/static/seed/js/controllers/mapping_controller.js
  seed/static/seed/js/services/uploader_service.js
  seed/static/seed/partials/data_upload_modal.html
Labels: Bug

#4757 Remove highlight from scenario
  seed/static/seed/partials/at_scenarios.html
  seed/static/seed/scss/style.scss
Labels: Bug

#4759 Standardize inventory detail display name
  seed/static/seed/js/controllers/analysis_details_controller.js
  seed/static/seed/js/controllers/inventory_detail_analyses_controller.js
  seed/static/seed/js/controllers/inventory_detail_cycles_controller.js
  seed/static/seed/js/controllers/inventory_detail_meters_controller.js
  seed/static/seed/js/controllers/inventory_detail_notes_modal_controller.js
  seed/static/seed/js/controllers/inventory_detail_sensors_controller.js
  seed/static/seed/js/controllers/inventory_detail_timeline_controller.js
  seed/static/seed/js/controllers/inventory_detail_ubid_controller.js
  seed/static/seed/js/controllers/notes_controller.js
  seed/static/seed/js/services/note_service.js
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/partials/inventory_detail_analyses.html
  seed/static/seed/partials/inventory_detail_cycles.html
  seed/static/seed/partials/inventory_detail_header.html
  seed/static/seed/partials/inventory_detail_meters.html
  seed/static/seed/partials/inventory_detail_sensors.html
  seed/static/seed/partials/inventory_detail_timeline.html
  seed/static/seed/partials/inventory_detail_ubid.html
  seed/static/seed/partials/notes.html
Labels: Bug

#4769 Exclude Column From Hash - Front End work and Rehash Job
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/data_importer/tasks.py
  seed/data_importer/tests/integration/test_merge_duplicate_rows.py
  seed/migrations/0225_column_is_excluded_from_hash.py
  seed/migrations/0226_rehash.py
  seed/models/columns.py
  seed/serializers/columns.py
  seed/static/seed/js/controllers/column_settings_controller.js
  seed/static/seed/js/controllers/confirm_column_settings_modal_controller.js
  seed/static/seed/js/services/columns_service.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/column_settings.html
  seed/static/seed/partials/confirm_column_settings_modal.html
  seed/static/seed/scss/style.scss
  seed/tasks.py
  seed/tests/test_column_views.py
  seed/tests/test_columns.py
  seed/tests/test_tasks.py
  seed/tests/test_views.py
  seed/views/v3/columns.py
Labels: Enhancement

#4783 DRY rehash
  seed/migrations/0111_rehash.py
  seed/migrations/0200_rehash.py
  seed/migrations/0223_water_use_columns.py
  seed/migrations/0226_rehash.py
  seed/utils/migrations.py
Labels: Maintenance

#4782 Improve handling of 2 factor authentication requirement
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/static/seed/js/controllers/two_factor_profile_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/two_factor_profile.html
Labels: Bug

#4794 Fix Django autoreload
  requirements/base.txt
Labels: Bug

#4792 Export CTS facility upload template for Federal BPS
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  requirements/base.txt
  seed/static/seed/js/controllers/export_to_cts_modal_controller.js
  seed/static/seed/js/services/inventory_service.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/export_to_cts_modal.html
  seed/static/seed/partials/inventory_list.html
  seed/static/seed/partials/organization_settings.html
  seed/static/seed/scss/style.scss
  seed/utils/CTS Facility Upload Template.xlsx
  seed/views/v3/properties.py
  seed/views/v3/tax_lot_properties.py
Labels: Feature

#4784 Removed helm charts
  charts/README.md
  charts/persistentvolumes/.helmignore
  charts/persistentvolumes/Chart.yaml
  charts/persistentvolumes/templates/_helpers.tpl
  charts/persistentvolumes/templates/seed-media-persistentvolumeclaim.yaml
  charts/persistentvolumes/templates/seed-pgdata-persistentvolumeclaim.yaml
  charts/persistentvolumes/values.yaml
  charts/seed/.helmignore
  charts/seed/Chart.yaml
  charts/seed/templates/NOTES.txt
  charts/seed/templates/_helpers.tpl
  charts/seed/templates/bsyncr-deployment.yaml
  charts/seed/templates/bsyncr-service.yaml
  charts/seed/templates/db-postgres-deployment.yaml
  charts/seed/templates/db-postgres-service.yaml
  charts/seed/templates/db-redis-deployment.yaml
  charts/seed/templates/redis-service.yaml
  charts/seed/templates/tests/test-connection.yaml
  charts/seed/templates/web-celery-deployment.yaml
  charts/seed/templates/web-celery-service.yaml
  charts/seed/templates/web-deployment.yaml
  charts/seed/templates/web-service.yaml
  charts/seed/values.yaml
  charts/values.yaml
Labels: Maintenance

#4798 Remove jwt oauth
  config/settings/common.py
  config/settings/local_untracked.py.dist
  config/urls.py
  requirements/base.txt
  seed/landing/models.py
  seed/migrations/0227_remove_oauth.py
  seed/utils/viewsets.py
Labels: Maintenance

#4771 Implement Building Upgrade Recommendation Analysis
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/analysis_pipelines/pipeline.py
  seed/analysis_pipelines/tasks.py
  seed/analysis_pipelines/upgrade_recommendation.py
  seed/migrations/0228_alter_analysis_service.py
  seed/models/analyses.py
  seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/analysis.html
  seed/static/seed/partials/analysis_run.html
  seed/static/seed/partials/inventory_detail_analyses_modal.html
  seed/static/seed/scss/style.scss
Labels: Feature

#4801 Added `COOKIE_EXPIRATION` environment variable
  config/settings/common.py
  deploy.sh
  docker-compose.local.yml
  docker-compose.yml
  docs/source/docker.rst
  docs/source/kubernetes_deployment.rst
Labels: Enhancement

#4780 Improvements to UBID handling during upload
  seed/data_importer/match.py
  seed/data_importer/tests/test_ah_import.py
  seed/data_importer/tests/test_match_incoming.py
  seed/lib/superperms/orgs/migrations/0039_alter_organization_ubid_threshold.py
  seed/lib/superperms/orgs/models.py
  seed/models/properties.py
  seed/models/tax_lots.py
  seed/serializers/organizations.py
  seed/static/seed/js/controllers/organization_settings_controller.js
  seed/static/seed/partials/organization_settings.html
  seed/tests/test_organization_utils.py
  seed/tests/test_organization_views.py
  seed/utils/organizations.py
  seed/utils/ubid.py
Labels: Bug

#4778 Add property measure class method defaults
  seed/audit_template/audit_template.py
  seed/models/property_measures.py
  seed/tests/test_measures.py
Labels: Bug

#4779 Delete events when related cycle is deleted.
  seed/migrations/0229_alter_event_cycle.py
  seed/models/events.py
  seed/static/seed/scss/style.scss
Labels: Bug

#4807 Updated GreenButton File Processing
  seed/lib/mcm/reader.py
  seed/tests/data/example-GreenButton-data2.xml
  seed/tests/test_greenbutton_import.py
Labels: Enhancement

#4802 Add move properties option to inventory actions dropdown
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/move_inventory_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/ah_service.js
  seed/static/seed/js/services/inventory_service.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/inventory_list.html
  seed/static/seed/partials/move_inventory_modal.html
  seed/templates/seed/_scripts.html
  seed/tests/test_property_views.py
  seed/views/v3/properties.py
Labels: Enhancement

#4805 Remaining Service Life table update
  requirements/base.txt
  seed/analysis_pipelines/element_statistics.py
  seed/analysis_pipelines/upgrade_recommendation.py
  seed/lib/tkbl/tkbl.py
  seed/serializers/elements.py
  seed/static/seed/js/services/element_service.js
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/scss/style.scss
  seed/views/v3/elements.py
Labels: Feature

#4808 Filter elements endpoint
  seed/utils/api_schema.py
  seed/views/v3/elements.py
Labels: Feature

#4740 Enable data type setting during data import
  seed/models/column_mapping_profiles.py
  seed/models/columns.py
  seed/static/seed/js/controllers/column_mappings_controller.js
  seed/static/seed/js/controllers/mapping_controller.js
  seed/static/seed/partials/column_mappings.html
  seed/static/seed/partials/mapping.html
  seed/tests/data/mappings/espm-single-mapping.csv
  seed/tests/data/test_datatype_mapping.csv
  seed/tests/test_columns.py
  seed/tests/test_goals.py
  seed/views/v3/column_mapping_profiles.py
Labels: Enhancement

#4763 Add derived data
  seed/audit_template/audit_template.py
  seed/data_importer/match.py
  seed/migrations/0229_add_extra_data_to_states.py
  seed/migrations/0230_alter_event_cycle.py
  seed/migrations/0231_column_is_updating.py
  seed/models/columns.py
  seed/models/properties.py
  seed/models/tax_lot_properties.py
  seed/models/tax_lots.py
  seed/serializers/columns.py
  seed/serializers/properties.py
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/update_derived_data_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/inventory_service.js
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/partials/inventory_list.html
  seed/static/seed/partials/update_derived_data_modal.html
  seed/static/seed/scss/style.scss
  seed/tasks.py
  seed/templates/seed/_scripts.html
  seed/tests/test_column_views.py
  seed/tests/test_columns.py
  seed/tests/test_derived_columns.py
  seed/tests/test_tax_lot_property.py
  seed/tests/test_views.py
  seed/utils/inventory_filter.py
  seed/views/v3/derived_columns.py
  seed/views/v3/properties.py
  seed/views/v3/tax_lot_properties.py
  seed/views/v3/taxlots.py
Labels: Enhancement

#4819 Fix rehash migrations prior to `is_excluded_from_hash`
  seed/data_importer/tasks.py
  seed/utils/migrations.py
Labels: Performance, Bug

#4818 Add Spanish translations
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.mo
  locale/es/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  script/get_angular_translations.sh
  script/get_python_translations.sh
  seed/static/seed/js/seed.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/es.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/about.html
  seed/static/seed/partials/contact.html
  seed/static/seed/partials/email_templates.html
  seed/static/seed/partials/home.html
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/partials/inventory_detail_header.html
  seed/static/seed/partials/program_setup.html
Labels: Feature

#4821 Fix `hiredis` not found error
  CHANGELOG.md
  requirements/base.txt
  seed/audit_template/__pycache__/audit_template.cpython-39.pyc.140134611837872
Labels: Bug
