Repository SEED-platform/seed, pull requests merged in 2024-10, with the labels that each got.

#4824 Fix
  seed/analysis_pipelines/element_statistics.py
Labels: Bug

#4726 Inventory groups
  seed/api/v3/urls.py
  seed/migrations/0232_inventorygroup_inventorygroupmapping.py
  seed/models/__init__.py
  seed/models/inventory_groups.py
  seed/serializers/inventory_groups.py
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_controller.js
  seed/static/seed/js/controllers/inventory_group_list_controller.js
  seed/static/seed/js/controllers/inventory_group_modal_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/update_inventory_groups_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/inventory_group_service.js
  seed/static/seed/js/services/inventory_service.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/partials/inventory_group_detail.html
  seed/static/seed/partials/inventory_group_detail_nav.html
  seed/static/seed/partials/inventory_group_modal.html
  seed/static/seed/partials/inventory_groups_list.html
  seed/static/seed/partials/inventory_list.html
  seed/static/seed/partials/inventory_nav.html
  seed/static/seed/partials/update_inventory_groups_modal.html
  seed/templates/seed/_scripts.html
  seed/tests/test_inventory_groups.py
  seed/utils/merge.py
  seed/views/v3/inventory_group_mappings.py
  seed/views/v3/inventory_groups.py
  seed/views/v3/properties.py
  seed/views/v3/taxlots.py
Labels: Feature, BEAM

#4827 Fix update display name
  seed/static/seed/js/controllers/confirm_column_settings_modal_controller.js
Labels: Bug

#4828 Fix scatter plot for non numeric x axis
  seed/static/seed/js/controllers/inventory_reports_controller.js
Labels: Bug

#4829 Fix cts export
  seed/views/v3/properties.py
Labels: Bug

#4820 Inventory groups frontend edits
  seed/migrations/0232_inventorygroup_inventorygroupmapping.py
  seed/models/inventory_groups.py
  seed/serializers/inventory_groups.py
  seed/serializers/properties.py
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_detail_meters_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_dashboard_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_meters_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_systems_controller.js
  seed/static/seed/js/controllers/inventory_group_list_controller.js
  seed/static/seed/js/controllers/inventory_group_modal_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/inventory_map_controller.js
  seed/static/seed/js/controllers/update_inventory_groups_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/inventory_group_service.js
  seed/static/seed/js/services/organization_service.js
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/partials/inventory_detail_header.html
  seed/static/seed/partials/inventory_detail_meters.html
  seed/static/seed/partials/inventory_group_detail_dashboard.html
  seed/static/seed/partials/inventory_group_detail_meters.html
  seed/static/seed/partials/inventory_group_detail_nav.html
  seed/static/seed/partials/inventory_group_detail_systems.html
  seed/static/seed/partials/inventory_group_modal.html
  seed/static/seed/partials/inventory_groups_list.html
  seed/static/seed/partials/inventory_list.html
  seed/static/seed/partials/inventory_map.html
  seed/static/seed/partials/update_inventory_groups_modal.html
  seed/static/seed/scss/style.scss
  seed/templates/seed/_scripts.html
  seed/tests/test_inventory_groups.py
  seed/tests/test_organization_access_levels.py
  seed/views/v3/access_levels.py
  seed/views/v3/inventory_group_mappings.py
  seed/views/v3/inventory_groups.py
  seed/views/v3/properties.py
  seed/views/v3/taxlots.py
Labels: Feature

#4831 Build axis data rollup table
  seed/static/seed/js/controllers/export_report_modal_controller.js
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/static/seed/js/services/inventory_reports_service.js
  seed/static/seed/partials/inventory_reports.html
  seed/views/v3/organizations.py
Labels: Enhancement

#4812 Add filter groups to default reports page
  Dockerfile
  Dockerfile-dev
  seed/models/filter_group.py
  seed/static/seed/js/controllers/export_report_modal_controller.js
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/inventory_reports_service.js
  seed/static/seed/partials/inventory_reports.html
  seed/tests/test_organization_views.py
  seed/views/v3/organizations.py
Labels: Enhancement

#4835 Fix rollup table
  seed/views/v3/organizations.py
Labels: Bug

#4830 More cts fixes
  seed/views/v3/properties.py
Labels: Bug

#4855 Lock sass dependency and enforce Node v20
  .github/workflows/ci.yml
  package-lock.json
  package.json
Labels: Bug

#4837 Add various inventory group features
  seed/models/tax_lot_properties.py
  seed/static/seed/js/controllers/inventory_group_modal_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/organization_service.js
  seed/static/seed/scss/style.scss
  seed/tasks.py
  seed/tests/test_inventory_groups.py
  seed/tests/test_organization_access_levels.py
  seed/utils/merge.py
  seed/views/v3/access_levels.py
  seed/views/v3/properties.py
  seed/views/v3/taxlots.py
Labels: Feature

#4845 Recheck for only numeric data in the rollup table
  seed/views/v3/organizations.py
Labels: Bug

#4839 include organization access_level_names in filter construction
  seed/models/filter_group.py
  seed/tests/test_filter_groups.py
Labels: Bug

#4857 Add meter import to sytems
  .github/workflows/ci.yml
  package-lock.json
  package.json
  seed/data_importer/meters_parser.py
  seed/data_importer/tasks.py
  seed/data_importer/tests/test_meters_parser.py
  seed/models/meters.py
  seed/serializers/meters.py
  seed/static/seed/js/controllers/green_button_upload_modal_controller.js
  seed/static/seed/js/controllers/inventory_detail_meters_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_meters_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_systems_controller.js
  seed/static/seed/js/controllers/service_modal_controller.js
  seed/static/seed/js/controllers/system_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/uploader_service.js
  seed/static/seed/partials/inventory_group_detail_systems.html
  seed/static/seed/partials/systems_table.html
  seed/tests/test_greenbutton_import.py
  seed/tests/test_import_file_views.py
  seed/tests/test_inventory_groups.py
  seed/tests/test_meter_usage_import.py
  seed/tests/test_meter_views.py
  seed/tests/test_property_views.py
  seed/views/v3/import_files.py
  seed/views/v3/organizations.py
  seed/views/v3/properties.py
Labels: Feature

#4859 Ensure year_built labels do not have commas, adjust width of scatterchart
  seed/static/seed/js/controllers/inventory_reports_controller.js
Labels: Bug

#4860 Systems and services fe edits
  .github/workflows/ci.yml
  package-lock.json
  package.json
  seed/api/v3/urls.py
  seed/data_importer/meters_parser.py
  seed/data_importer/tasks.py
  seed/data_importer/tests/test_meters_parser.py
  seed/lib/superperms/orgs/decorators.py
  seed/migrations/0233_auto_20241004_1413.py
  seed/migrations/0234_auto_20241008_1510.py
  seed/migrations/0235_meter_systems.py
  seed/models/__init__.py
  seed/models/meters.py
  seed/models/systems.py
  seed/serializers/meters.py
  seed/serializers/systems.py
  seed/static/seed/js/controllers/green_button_upload_modal_controller.js
  seed/static/seed/js/controllers/inventory_detail_meters_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_meters_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_systems_controller.js
  seed/static/seed/js/controllers/service_modal_controller.js
  seed/static/seed/js/controllers/system_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/service_service.js
  seed/static/seed/js/services/system_service.js
  seed/static/seed/js/services/uploader_service.js
  seed/static/seed/partials/inventory_group_detail_meters.html
  seed/static/seed/partials/inventory_group_detail_systems.html
  seed/static/seed/partials/service_modal.html
  seed/static/seed/partials/services_table.html
  seed/static/seed/partials/system_modal.html
  seed/static/seed/partials/systems_table.html
  seed/static/seed/scss/style.scss
  seed/templates/seed/_scripts.html
  seed/test_helpers/fake.py
  seed/tests/test_greenbutton_import.py
  seed/tests/test_import_file_views.py
  seed/tests/test_inventory_groups.py
  seed/tests/test_meter_usage_import.py
  seed/tests/test_meter_views.py
  seed/tests/test_property_views.py
  seed/tests/test_services.py
  seed/tests/test_systems.py
  seed/views/v3/import_files.py
  seed/views/v3/inventory_groups.py
  seed/views/v3/organizations.py
  seed/views/v3/properties.py
  seed/views/v3/services.py
  seed/views/v3/systems.py
Labels: Feature

#4867 Speed up pm meters preview
  seed/data_importer/meters_parser.py
  seed/data_importer/tests/test_meters_parser.py
  seed/tests/test_meter_usage_import.py
Labels: Enhancement

#4864 Add derived columns to default reports
  seed/views/v3/organizations.py
Labels: Enhancement

#4871 Create a mechanism to save report configurations to a named slots
  seed/api/v3/urls.py
  seed/migrations/0232_reportconfiguration.py
  seed/models/__init__.py
  seed/models/report_configurations.py
  seed/serializers/report_configurations.py
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/static/seed/js/controllers/report_configuration_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/report_configurations_service.js
  seed/static/seed/partials/inventory_reports.html
  seed/static/seed/partials/report_configuration_modal.html
  seed/templates/seed/_scripts.html
  seed/tests/test_report_configurations.py
  seed/views/v3/organizations.py
  seed/views/v3/report_configurations.py
Labels: Enhancement

#4873 update building upgrade rec modal
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.mo
  locale/es/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/analysis_pipelines/upgrade_recommendation.py
  seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/es.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/inventory_detail_analyses_modal.html
Labels: Enhancement

#4872 Add zoom/pan capability to report charting, add reset zoom buttons
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/static/seed/partials/inventory_reports.html
Labels: Enhancement

#4862 Updates to portfolio summary
  seed/models/data_quality.py
  seed/static/seed/js/controllers/portfolio_summary_controller.js
  seed/static/seed/js/services/inventory_service.js
  seed/utils/goals.py
  seed/utils/inventory_filter.py
  seed/utils/search.py
Labels: Feature
