Repository SEED-platform/seed, pull requests merged in 2024-07, with the labels that each got.

#4705 Fix timeline user display
  seed/static/seed/js/controllers/inventory_detail_timeline_controller.js
Labels: Enhancement

#4689 Add Elements and initial TKBL functionality
  .cspell.json
  requirements/base.txt
  seed/api/v3/urls.py
  seed/data_importer/tests/test_ah_import.py
  seed/lib/tkbl/tkbl.py
  seed/lib/uniformat/uniformat.py
  seed/migrations/0218_elements.py
  seed/migrations/0219_auto_20240604_1605.py
  seed/models/__init__.py
  seed/models/columns.py
  seed/models/elements.py
  seed/models/uniformat.py
  seed/serializers/elements.py
  seed/serializers/uniformat.py
  seed/static/seed/js/controllers/column_settings_controller.js
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_detail_timeline_controller.js
  seed/static/seed/js/controllers/unmerge_modal_controller.js
  seed/static/seed/js/filters/startCase.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/element_service.js
  seed/static/seed/js/services/note_service.js
  seed/static/seed/js/services/uniformat_service.js
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/partials/mapping.html
  seed/static/seed/partials/unmerge_modal.html
  seed/static/seed/scss/style.scss
  seed/static/seed/tests/dataset_detail_controller.spec.js
  seed/static/seed/tests/dataset_list_controller.spec.js
  seed/static/seed/tests/inventory_detail_controller.spec.js
  seed/static/seed/tests/property_detail_controller.spec.js
  seed/static/seed/tests/sdUploader.spec.js
  seed/static/seed/tests/taxlot_detail_controller.spec.js
  seed/templates/seed/_scripts.html
  seed/test_helpers/fake.py
  seed/tests/test_column_views.py
  seed/tests/test_element_views.py
  seed/tests/test_elements.py
  seed/tests/test_labels_api_views.py
  seed/tests/test_meter_views.py
  seed/tests/test_note_views.py
  seed/utils/api.py
  seed/utils/api_schema.py
  seed/utils/merge.py
  seed/utils/pagination.py
  seed/views/v3/elements.py
  seed/views/v3/uniformat.py
Labels: Feature, ESTCP

#4703 Filter analyses by cycle
  seed/tests/test_analyses_views.py
  seed/views/v3/properties.py
Labels: Enhancement

#4679 BETTER v1.7 updates
  seed/analysis_pipelines/better/buildingsync.py
  seed/analysis_pipelines/better/pipeline.py
  seed/analysis_pipelines/utils.py
  seed/models/analyses.py
Labels: Bug, BETTER

#4716 Fix reports with `None` values
  seed/views/v3/organizations.py
Labels: Bug

#4715 Fix UBID matching behavior
  package-lock.json
  package.json
  seed/data_importer/match.py
  seed/data_importer/models.py
  seed/data_importer/tasks.py
  seed/data_importer/tests/test_ah_import.py
  seed/utils/match.py
  seed/utils/ubid.py
Labels: Bug

#4652 Lock pandas sub-dependency and update pytz
  requirements/base.txt
Labels: Maintenance

#4718 Major import performance improvements
  seed/data_importer/match.py
  seed/tests/test_match_existing.py
  seed/tests/test_property_views.py
  seed/tests/test_taxlot_views.py
  seed/utils/match.py
  seed/utils/ubid.py
  seed/views/properties.py
  seed/views/v3/organizations.py
  seed/views/v3/properties.py
  seed/views/v3/taxlots.py
Labels: Performance

#4727 Fix missing inventory detail sections
  seed/static/seed/partials/inventory_detail.html
Labels: Bug

#4729 dont make non numbers numerical
  seed/models/tax_lot_properties.py
Labels: Bug
