Repository SEED-platform/seed, pull requests merged in 2024-02, with the labels that each got.

#4499 Fix program setup's new program button action
  seed/static/seed/js/controllers/program_setup_controller.js
  seed/static/seed/partials/program_setup.html
Labels: Bug

#4512 Restrict leaf user permissions for goals
  seed/docs/views.py
  seed/lib/superperms/orgs/decorators.py
  seed/static/seed/js/controllers/goal_editor_modal_controller.js
  seed/static/seed/js/controllers/menu_controller.js
  seed/static/seed/js/controllers/portfolio_summary_controller.js
  seed/static/seed/js/services/user_service.js
  seed/static/seed/partials/goal_editor_modal.html
  seed/static/seed/partials/portfolio_summary.html
  seed/templates/seed/base.html
  seed/tests/test_account_views.py
  seed/tests/test_goals.py
  seed/views/main.py
  seed/views/v3/goals.py
Labels: Enhancement

#4514 Add year built to goal table
  seed/static/seed/js/controllers/portfolio_summary_controller.js
Labels: Enhancement

#4516 Set default property if goal property is undefined
  seed/static/seed/js/controllers/portfolio_summary_controller.js
Labels: Bug

#4517 Ah/fix ali assignment
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/data_importer/tasks.py
  seed/static/seed/js/services/organization_service.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/organization_access_level_tree.html
  seed/static/seed/scss/style.scss
  seed/views/v3/access_levels.py
Labels: Enhancement, Bug

#4518 Hierarchy data type improvements
  seed/static/seed/images/ali-tree-example-lg.png
  seed/static/seed/images/ali-tree-example-lg.webp
  seed/static/seed/js/controllers/insights_property_controller.js
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/mapping_controller.js
  seed/static/seed/js/controllers/organization_add_access_level_instance_modal_controller.js
  seed/static/seed/js/controllers/organization_delete_access_level_instance_modal_controller.js
  seed/static/seed/js/services/inventory_service.js
  seed/static/seed/js/services/organization_service.js
  seed/static/seed/js/services/user_service.js
  seed/static/seed/partials/inventory_list.html
  seed/static/seed/partials/organization_access_level_tree.html
  seed/templates/seed/base.html
Labels: Enhancement, Bug

#4449 Labels: Added complex filtering logic
  seed/migrations/0212_add_filtergroup_labels.py
  seed/migrations/0213_move_filtergroup_labels.py
  seed/migrations/0214_delete_filtergroup_labels.py
  seed/models/data_views.py
  seed/models/filter_group.py
  seed/serializers/filter_groups.py
  seed/static/seed/js/controllers/filter_group_modal_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/services/inventory_service.js
  seed/static/seed/partials/inventory_list.html
  seed/tests/test_data_view_views.py
  seed/tests/test_filter_groups.py
  seed/views/v3/filter_group.py
Labels: Filtering, Inventory List, Enhancement, Clearly Energy, BEAM Implemented

#4520 Rename goal detail headers
  seed/static/seed/js/controllers/portfolio_summary_controller.js
Labels: Maintenance

#4202 Add Permissions to PropertyViewSet
  seed/lib/superperms/orgs/decorators.py
  seed/tests/api/test_modules.py
  seed/tests/test_property_views_viewset.py
  seed/views/v3/property_views.py
Labels: Feature, Acct. Hierarchy

#4522 Enable background progress for uploading AH levels
  seed/data_importer/tasks.py
  seed/lib/progress_data/progress_data.py
  seed/lib/superperms/orgs/models.py
Labels: Enhancement

#4523 ignore duplicates when adding labels
  seed/views/v3/label_inventories.py
Labels: Bug

#4495 Disallow manual merge of records with different alis
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/merge_modal_controller.js
  seed/tests/api/seed_readingtools.py
  seed/tests/test_property_views.py
  seed/tests/test_taxlot_views.py
  seed/utils/match.py
  seed/utils/merge.py
  seed/views/v3/properties.py
  seed/views/v3/taxlots.py
Labels: Bug

#4526 fix 403 error for viewer role
  seed/views/v3/organizations.py
Labels: Bug

#4527 Inventor List - Ignore incomplete filters containing just an operator
  seed/static/seed/js/controllers/inventory_list_controller.js
Labels: Bug

#4376 Redis backend update
  .cspell.json
  config/settings/docker.py
  config/settings/docker_dev.py
  config/settings/local_untracked.py.dist
  config/settings/test_local_untracked.py
  docs/source/aws.rst
  docs/source/linux.rst
  docs/source/migrations.rst
  docs/source/setup_osx.rst
  requirements/base.txt
Labels: Feature

#4528 Inventory Map - Fix positioning of the popup tooltip to be closer to the pin
  seed/static/seed/js/controllers/inventory_map_controller.js
Labels: Bug

#4519 Handle ali links during import
  seed/data_importer/match.py
  seed/data_importer/tests/test_AH_import.py
  seed/data_importer/tests/test_match_incoming.py
  seed/tests/test_match_existing.py
  seed/tests/test_property_views.py
  seed/tests/test_taxlot_views.py
  seed/utils/match.py
  seed/views/properties.py
  seed/views/v3/organizations.py
  seed/views/v3/properties.py
  seed/views/v3/taxlots.py
Labels: Enhancement

#4533 Update error message on overlapping reading import
  seed/data_importer/tasks.py
  seed/tests/test_greenbutton_import.py
  seed/tests/test_meter_usage_import.py
Labels: Bug

#4534 Fix Redis compatibility with boto3
  requirements/aws.txt
  requirements/base.txt
Labels: Bug

#4537 Reject import file if it contains braces
  seed/data_importer/tasks.py
Labels: Bug

#4540 AH - display matching criteria warning when user uploads data to the org for the first time
  .github/workflows/ci.yml
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/static/seed/js/controllers/create_sub_organization_modal_controller.js
  seed/static/seed/js/controllers/data_upload_modal_controller.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/create_sub_organization_modal.html
  seed/static/seed/partials/data_upload_modal.html
  seed/static/seed/scss/style.scss
  seed/static/seed/tests/data_upload_modal_controller.spec.js
Labels: Enhancement

#4541 AH - Fix level 1 Access Level display in Inventory Details Page table
  seed/static/seed/js/controllers/inventory_detail_controller.js
Labels: Bug

#4532 Add notes related to goals
  seed/api/v3/urls.py
  seed/migrations/0217_goalnote.py
  seed/migrations/0218_historicalnote.py
  seed/models/__init__.py
  seed/models/goal_notes.py
  seed/models/goals.py
  seed/models/notes.py
  seed/models/properties.py
  seed/models/tax_lot_properties.py
  seed/serializers/goal_notes.py
  seed/serializers/historical_notes.py
  seed/static/seed/js/controllers/portfolio_summary_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/goal_service.js
  seed/static/seed/js/services/inventory_service.js
  seed/static/seed/partials/portfolio_summary.html
  seed/static/seed/scss/style.scss
  seed/tests/test_goals.py
  seed/utils/inventory_filter.py
  seed/utils/viewsets.py
  seed/views/v3/goal_notes.py
  seed/views/v3/historical_notes.py
Labels: Feature

#4542 Fix default report X and Y axis selectors
  seed/static/seed/partials/inventory_reports.html
  seed/utils/generic.py
  seed/views/v3/organizations.py
Labels: Bug

#4543 Delete alis with als
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/static/seed/js/controllers/organization_access_level_tree_controller.js
  seed/static/seed/js/controllers/organization_add_access_level_modal_controller.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/organization_add_access_level_modal.html
  seed/static/seed/scss/style.scss
  seed/tests/test_organization_access_levels.py
  seed/views/v3/access_levels.py
Labels: Enhancement

#4496 Apply unit conversion to extra data
  seed/models/tax_lot_properties.py
  seed/serializers/pint.py
  seed/views/v3/import_files.py
Labels: Bug

#4546 Several AH bug fixes
  seed/management/commands/create_default_user.py
  seed/static/seed/js/controllers/admin_controller.js
  seed/static/seed/js/controllers/goal_editor_modal_controller.js
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/new_member_modal_controller.js
  seed/static/seed/js/controllers/organization_add_access_level_instance_modal_controller.js
  seed/static/seed/js/controllers/portfolio_summary_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/ah_service.js
  seed/static/seed/partials/inventory_detail.html
  seed/templates/seed/_header.html
  seed/templates/seed/_scripts.html
  seed/utils/inventory_filter.py
  seed/views/v3/organization_users.py
Labels: Maintenance, Enhancement, Bug

#4554 Handle empty cycles on portfolio summary
  seed/static/seed/js/controllers/portfolio_summary_controller.js
Labels: Bug

#4551 AH - Revise analysis permissions for creating columns
  seed/analysis_pipelines/better/pipeline.py
  seed/analysis_pipelines/co2.py
  seed/analysis_pipelines/eeej.py
  seed/analysis_pipelines/eui.py
  seed/lib/superperms/orgs/models.py
  seed/models/analyses.py
  seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/tests/test_analysis_pipelines.py
Labels: Enhancement

#4555 Fix unit conversion for non numeric values
  seed/models/tax_lot_properties.py
  seed/tests/test_analysis_pipelines.py
  seed/tests/test_columns.py
  seed/tests/test_tax_lot_property.py
Labels: Bug
