Repository SEED-platform/seed, pull requests merged in 2024-03, with the labels that each got.

#4552 Allow change of ali
  seed/static/seed/js/controllers/members_controller.js
  seed/static/seed/js/services/organization_service.js
  seed/static/seed/partials/members.html
  seed/static/seed/tests/members_controller.spec.js
  seed/tests/test_account_views.py
  seed/views/v3/organization_users.py
  seed/views/v3/users.py
Labels: Feature, Acct. Hierarchy

#4556 review viewer permissions
  seed/lib/superperms/orgs/decorators.py
  seed/static/seed/js/controllers/analyses_controller.js
  seed/static/seed/js/controllers/inventory_detail_analyses_controller.js
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_detail_meters_controller.js
  seed/static/seed/js/controllers/inventory_detail_sensors_controller.js
  seed/static/seed/js/controllers/inventory_detail_settings_controller.js
  seed/static/seed/js/controllers/inventory_detail_timeline_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/inventory_list_legacy_controller.js
  seed/static/seed/js/controllers/inventory_settings_controller.js
  seed/static/seed/js/controllers/notes_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/partials/analyses.html
  seed/static/seed/partials/analysis_card.html
  seed/static/seed/partials/at_scenarios.html
  seed/static/seed/partials/insights_property.html
  seed/static/seed/partials/inventory_detail.html
  seed/static/seed/partials/inventory_detail_analyses.html
  seed/static/seed/partials/inventory_detail_meters.html
  seed/static/seed/partials/inventory_detail_sensors.html
  seed/static/seed/partials/inventory_detail_settings.html
  seed/static/seed/partials/inventory_list.html
  seed/static/seed/partials/inventory_list_legacy.html
  seed/static/seed/partials/inventory_settings.html
  seed/static/seed/partials/notes.html
  seed/static/seed/partials/ubid_admin.html
  seed/static/seed/scss/style.scss
  seed/tests/test_ubids.py
  seed/views/v3/analyses.py
  seed/views/v3/notes.py
  seed/views/v3/organization_users.py
  seed/views/v3/organizations.py
  seed/views/v3/properties.py
  seed/views/v3/ubid.py
Labels: Bug

#4545 Disallow changing nonroot users to owner
  seed/static/seed/js/controllers/members_controller.js
  seed/static/seed/js/controllers/new_member_modal_controller.js
  seed/static/seed/partials/members.html
  seed/static/seed/partials/new_member_modal.html
  seed/static/seed/tests/new_member_modal_controller.spec.js
  seed/views/v3/users.py
Labels: Bug

#4557 Fix portfolio summary editable cells
  seed/static/seed/js/controllers/portfolio_summary_controller.js
  seed/static/seed/scss/style.scss
Labels: Bug

#4378 Permission
  seed/views/v3/data_quality_checks.py
Labels: Enhancement, Acct. Hierarchy

#4560 Squash Accountability Hierarchy Migrations
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  seed/data_importer/migrations/0019_accountability_hierarchy.py
  seed/data_importer/tasks.py
  seed/lib/superperms/orgs/migrations/0029_auto_20240105_1257.py
  seed/lib/superperms/orgs/migrations/0030_accountability_hierarchy.py
  seed/migrations/0212_add_filtergroup_labels.py
  seed/migrations/0212_auto_add_props_to_tree_squashed_0213_analysis_access_level_instance.py
  seed/migrations/0213_move_filtergroup_labels.py
  seed/migrations/0214_delete_filtergroup_labels.py
  seed/migrations/0215_accountability_hierarchy.py
  seed/migrations/0216_goal.py
  seed/migrations/0217_goalnote.py
  seed/migrations/0218_historicalnote.py
  seed/models/data_quality.py
  seed/models/tax_lot_properties.py
  seed/serializers/pint.py
  seed/tests/test_analysis_pipelines.py
  seed/tests/test_columns.py
  seed/tests/test_tax_lot_property.py
  seed/views/v3/import_files.py
  vendors/package-lock.json
Labels: Enhancement

#4565 Fix categorical axis
  seed/static/seed/js/controllers/insights_property_controller.js
Labels: Bug

#4566 Fix portfolio summary layout
  seed/static/seed/js/controllers/portfolio_summary_controller.js
  seed/static/seed/partials/portfolio_summary.html
  seed/static/seed/scss/style.scss
Labels: Enhancement, Bug

#4568 Better co2 Analysis error message
  seed/analysis_pipelines/co2.py
Labels: Enhancement

#4563 Allow data logger deleteion
  seed/lib/superperms/orgs/decorators.py
  seed/static/seed/js/controllers/delete_data_logger_modal_controller.js
  seed/static/seed/js/controllers/inventory_detail_sensors_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/sensor_service.js
  seed/static/seed/partials/delete_data_logger_modal.html
  seed/templates/seed/_scripts.html
  seed/tests/test_property_views.py
  seed/views/v3/data_logger.py
Labels: Feature

#4576 Redirect on org change if necessary
  seed/static/seed/js/controllers/menu_controller.js
Labels: Bug

#4571 Feature/upgrade codebuild http2
  Dockerfile
  Makefile
  awscodebuild/buildspec.yml
  docker-compose.yml
  docker/nginx/nginx.conf.template
Labels: Maintenance

#4579 Fix property search endpoint in Swagger
  seed/views/v3/properties.py
Labels: Bug

#4572 Limit member visibility to users within access level instance
  seed/static/seed/partials/members.html
  seed/tests/test_organization_users.py
  seed/views/v3/organization_users.py
Labels: Enhancement

#4577 Allow jurisdiction_tax_lot_id display name change
  seed/data_importer/tasks.py
  seed/models/column_mappings.py
Labels: Bug

#4561 Allow sensor deletion
  seed/api/v3/urls.py
  seed/static/seed/js/controllers/inventory_detail_sensors_controller.js
  seed/static/seed/js/controllers/sensor_delete_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/sensor_service.js
  seed/static/seed/partials/sensor_delete_modal.html
  seed/templates/seed/_scripts.html
  seed/tests/test_property_views.py
  seed/tests/test_sensors.py
  seed/views/v3/properties.py
  seed/views/v3/sensors.py
Labels: Feature

#4583 Allow data logger update
  seed/static/seed/js/controllers/data_logger_upload_or_update_modal_controller.js
  seed/static/seed/js/controllers/delete_data_logger_modal_controller.js
  seed/static/seed/js/controllers/inventory_detail_sensors_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/sensor_service.js
  seed/static/seed/partials/data_logger_upload_or_update_modal.html
  seed/static/seed/partials/inventory_detail_sensors.html
  seed/templates/seed/_scripts.html
  seed/tests/test_sensors.py
  seed/views/v3/data_logger.py
Labels: Enhancement

#4584 Allow sensor update
  seed/migrations/0215_alter_sensor_unique_together.py
  seed/models/sensors.py
  seed/static/seed/js/controllers/inventory_detail_sensors_controller.js
  seed/static/seed/js/controllers/sensor_update_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/sensor_service.js
  seed/static/seed/partials/sensor_update_modal.html
  seed/templates/seed/_scripts.html
  seed/tests/test_sensors.py
  seed/views/v3/sensors.py
Labels: Enhancement

#4587 Dont shorten lat/long
  seed/static/seed/js/controllers/inventory_list_controller.js
Labels: Feature

#4588 Empty label section remains same size when toggled
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/portfolio_summary_controller.js
  seed/static/seed/scss/style.scss
Labels: Enhancement

#4593 Allow superusers to list all org members
  seed/views/v3/organization_users.py
Labels: Bug

#4598 Update to latest version of UBID library
  requirements/base.txt
Labels: Maintenance

#4590 Updated Swagger config to prevent requesting external schemas
  config/settings/common.py
  seed/templates/drf-yasg/swagger-ui.html
Labels: Bug

#4580 Update Node in Docker images
  Dockerfile
  Dockerfile-dev
Labels: Maintenance

#4591 Clear invalid label tags
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/partials/inventory_list.html
Labels: Bug

#4594 Show error on custom reports if no filter groups exist
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/data_view.html
  seed/static/seed/scss/style.scss
Labels: Bug
