Repository SEED-platform/seed, pull requests merged in 2024-05, with the labels that each got.

#4654 Speed up ali tree
  seed/lib/superperms/orgs/models.py
  seed/lib/superperms/tests/test_organization_access_levels.py
  seed/static/seed/js/controllers/members_controller.js
  seed/static/seed/js/controllers/organization_add_access_level_modal_controller.js
  seed/static/seed/js/services/ah_service.js
  seed/static/seed/partials/organization_access_level_tree.html
  seed/tests/test_organization_access_levels.py
  seed/views/v3/access_levels.py
Labels: Enhancement

#4650 Docker upgrade database
  docker-compose.build.yml
  docker-compose.dev.yml
  docker-compose.local.yml
  docker-compose.pgupgrade.yml
  docker-compose.yml
  docker/dump_database.sh
  docker/postgres_upgrade.sh
  docker/restore_database.sh
Labels: Feature

#4651 Postgres 16 upgrade documentation
  docs/source/postgres_upgrade.rst
Labels: Documentation

#4642 Fix email
  seed/static/seed/js/controllers/inventory_list_controller.js
Labels: Bug

#4666 Update portfolio summary
  seed/migrations/0217_goal_commitment_sqft.py
  seed/models/goals.py
  seed/static/seed/js/controllers/bulk_edit_goalnotes_modal_controller.js
  seed/static/seed/js/controllers/goal_editor_modal_controller.js
  seed/static/seed/js/controllers/portfolio_summary_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/goal_service.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/bulk_edit_goalnotes_modal.html
  seed/static/seed/partials/goal_editor_modal.html
  seed/static/seed/partials/portfolio_summary.html
  seed/static/seed/scss/style.scss
  seed/templates/seed/_scripts.html
  seed/tests/test_goals.py
  seed/utils/goal_notes.py
  seed/utils/goals.py
  seed/views/v3/goal_notes.py
  seed/views/v3/goals.py
Labels: Feature

#4683 Replaced missing ESPM report
  seed/tests/test_portfoliomanager.py
  seed/views/v3/portfolio_manager.py
Labels: Bug

#4672 Fix has meter indicator
  seed/models/tax_lot_properties.py
Labels: Bug

#4681 Set default portfolio summary cell type
  seed/static/seed/js/controllers/portfolio_summary_controller.js
Labels: Bug

#4686 Nginx brotli compression
  Dockerfile
  config/settings/common.py
  docker/nginx/nginx.conf.template
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/landing/static/landing/scss/fonts.scss
  seed/landing/templates/landing/base.html
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/templates/seed/_fonts.html
  seed/templates/seed/base.html
Labels: Enhancement
