Repository SEED-platform/seed, pull requests merged in 2024-08, with the labels that each got.

#4721 Hannah/analysis
  seed/analysis_pipelines/element_statistics.py
  seed/analysis_pipelines/pipeline.py
  seed/analysis_pipelines/tasks.py
  seed/migrations/0220_alter_analysis_service.py
  seed/models/analyses.py
  seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
  seed/static/seed/partials/inventory_detail_analyses_modal.html
Labels: Feature

#4620 Add AT submission import
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/api/v3/urls.py
  seed/audit_template/__pycache__/audit_template.cpython-39.pyc.140134611837872
  seed/audit_template/audit_template.py
  seed/lib/superperms/orgs/migrations/0034_org_audit_template_fields.py
  seed/lib/superperms/orgs/models.py
  seed/migrations/0221_audittemplateconfig.py
  seed/models/__init__.py
  seed/models/audit_template_configs.py
  seed/serializers/audit_template_configs.py
  seed/serializers/data_loggers.py
  seed/static/seed/js/controllers/at_submission_import_modal_controller.js
  seed/static/seed/js/controllers/data_logger_upload_or_update_modal_controller.js
  seed/static/seed/js/controllers/data_upload_audit_template_modal_controller.js
  seed/static/seed/js/controllers/data_upload_modal_controller.js
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/organization_settings_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/audit_template_service.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/at_submission_import_modal.html
  seed/static/seed/partials/data_logger_upload_or_update_modal.html
  seed/static/seed/partials/data_upload_audit_template_modal.html
  seed/static/seed/partials/data_upload_modal.html
  seed/static/seed/partials/export_to_audit_template_modal.html
  seed/static/seed/partials/inventory_list.html
  seed/static/seed/partials/organization_settings.html
  seed/static/seed/scss/style.scss
  seed/static/seed/tests/settings_controller.spec.js
  seed/tasks.py
  seed/templates/seed/_scripts.html
  seed/tests/test_account_views.py
  seed/tests/test_audit_template.py
  seed/tests/test_audit_template_configs.py
  seed/tests/test_views.py
  seed/views/v3/audit_template.py
  seed/views/v3/audit_template_configs.py
  seed/views/v3/data_logger.py
  seed/views/v3/organizations.py
  seed/views/v3/properties.py
Labels: Feature

#4700 Add 2 Factor Authentication
  config/settings/common.py
  config/urls.py
  requirements/base.txt
  seed/api/v3/urls.py
  seed/context_processors.py
  seed/landing/migrations/0008_seeduser_prompt_2fa.py
  seed/landing/models.py
  seed/landing/static/landing/scss/landing.scss
  seed/landing/templates/landing/account_activation_invalid.html
  seed/landing/templates/landing/account_activation_sent.html
  seed/landing/templates/landing/create_account.html
  seed/landing/templates/landing/home.html
  seed/landing/templates/landing/password_reset_confirm.html
  seed/landing/templates/landing/password_reset_done.html
  seed/landing/templates/landing/signup.html
  seed/landing/templates/landing/thank_you.html
  seed/landing/templates/two_factor/_base.html
  seed/landing/templates/two_factor/_base_focus.html
  seed/landing/templates/two_factor/_wizard_actions.html
  seed/landing/templates/two_factor/_wizard_forms.html
  seed/landing/templates/two_factor/core/backup_tokens.html
  seed/landing/templates/two_factor/core/login.html
  seed/landing/templates/two_factor/core/otp_required.html
  seed/landing/templates/two_factor/core/phone_register.html
  seed/landing/templates/two_factor/core/setup.html
  seed/landing/templates/two_factor/core/setup_complete.html
  seed/landing/templates/two_factor/profile/disable.html
  seed/landing/templates/two_factor/profile/profile.html
  seed/landing/templates/two_factor/twilio/sms_message.html
  seed/landing/tests.py
  seed/landing/urls.py
  seed/landing/views.py
  seed/lib/superperms/orgs/migrations/0035_organization_require_2fa.py
  seed/lib/superperms/orgs/models.py
  seed/static/seed/js/controllers/qr_code_scan_modal_controller.js
  seed/static/seed/js/controllers/two_factor_profile_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/two_factor_service.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/organization_settings.html
  seed/static/seed/partials/profile_nav.html
  seed/static/seed/partials/qr_code_scan_modal.html
  seed/static/seed/partials/two_factor_profile.html
  seed/static/seed/scss/style.scss
  seed/templates/seed/_scripts.html
  seed/tests/test_account_views.py
  seed/utils/organizations.py
  seed/utils/two_factor.py
  seed/views/v3/organizations.py
  seed/views/v3/two_factor_views.py
  seed/views/v3/users.py
Labels: Feature

#4739 add helptext to default reports controls at top of page
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/inventory_reports.html
Labels: Enhancement

#4741 Allow all users to save two factor auth settings
  seed/static/seed/js/controllers/two_factor_profile_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/partials/two_factor_profile.html
  seed/utils/organizations.py
  seed/views/v3/users.py
Labels: Bug

#4733 Clean up default reports
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/static/seed/js/controllers/organization_settings_controller.js
  seed/static/seed/js/services/inventory_reports_service.js
  seed/views/v3/organizations.py
Labels: Bug

#4695 Add cross cycle data quality checks
  seed/api/v3/urls.py
  seed/data_importer/tasks.py
  seed/migrations/0222_cross_cycle_data_quality.py
  seed/models/columns.py
  seed/models/data_quality.py
  seed/models/models.py
  seed/models/properties.py
  seed/serializers/property_view_labels.py
  seed/serializers/rules.py
  seed/static/seed/js/controllers/data_quality_admin_controller.js
  seed/static/seed/js/controllers/data_quality_modal_controller.js
  seed/static/seed/js/controllers/delete_modal_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/portfolio_summary_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/data_quality_service.js
  seed/static/seed/js/services/label_service.js
  seed/static/seed/partials/accounts.html
  seed/static/seed/partials/accounts_nav.html
  seed/static/seed/partials/data_quality_admin.html
  seed/static/seed/partials/portfolio_summary.html
  seed/static/seed/scss/style.scss
  seed/static/seed/tests/data_quality_admin_controller.spec.js
  seed/templates/seed/_header.html
  seed/test_helpers/fake.py
  seed/tests/test_data_quality_check_rules_views.py
  seed/tests/test_data_quality_checks.py
  seed/tests/test_labels_api_views.py
  seed/tests/test_property_view_labels.py
  seed/utils/goals.py
  seed/utils/labels.py
  seed/utils/merge.py
  seed/views/v3/data_quality_checks.py
  seed/views/v3/label_inventories.py
  seed/views/v3/property_view_labels.py
Labels: Feature

#4744 Add messages for reasons the save button on column mappings is disabled
  seed/static/seed/js/controllers/column_mappings_controller.js
  seed/static/seed/partials/column_mappings.html
Labels: Bug

#4742 update filter AND OR placeholder text
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/inventory_list.html
Labels: Enhancement

#4731 Fix bug preventing tax lot columns from moving
  seed/static/seed/js/controllers/inventory_list_controller.js
Labels: Bug

#4709 Display errors on the front end for bad mapquest keys when geocoding
  seed/static/seed/js/controllers/geocode_modal_controller.js
  seed/tests/test_geocode_views.py
  seed/utils/geocode.py
  seed/views/v3/geocode.py
Labels: Bug

#4760 Fix Salesforce Tests
  seed/tests/test_salesforce_views.py
Labels: Bug

#4754 Doubled rehash performance
  seed/data_importer/tasks.py
  seed/management/commands/rehash.py
  seed/migrations/0223_water_use_columns.py
Labels: Performance, Bug

#4758 Fix username case sensitivity
  seed/landing/views.py
Labels: Bug

#4753 Handle BETTER terms and conditions error
  seed/analysis_pipelines/better/client.py
  seed/analysis_pipelines/better/pipeline.py
  seed/static/seed/js/controllers/inventory_detail_analyses_modal_controller.js
  seed/static/seed/js/controllers/organization_settings_controller.js
  seed/static/seed/js/services/analyses_service.js
  seed/static/seed/partials/inventory_detail_analyses_modal.html
  seed/static/seed/partials/organization_settings.html
  seed/views/v3/analyses.py
Labels: Feature

#4680 Add to CTS button
  requirements/base.txt
  seed/building_sync/tests/data/ExportedData.xlsx
  seed/static/seed/js/controllers/export_to_cts_modal_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/inventory_service.js
  seed/static/seed/partials/export_to_cts_modal.html
  seed/static/seed/partials/inventory_list.html
  seed/templates/seed/_scripts.html
  seed/views/v3/tax_lot_properties.py
Labels: Feature

#4756 Speed up step 6
  seed/data_importer/match.py
  seed/data_importer/tests/test_match_incoming.py
  seed/utils/match.py
Labels: Enhancement

#4750 Add ability to retrieve all Audit Template submissions
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/audit_template/audit_template.py
  seed/lib/superperms/orgs/migrations/0038_alter_organization_audit_template_status_type.py
  seed/lib/superperms/orgs/models.py
  seed/static/seed/js/controllers/organization_settings_controller.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/organization_settings.html
  seed/static/seed/scss/style.scss
  seed/tests/test_account_views.py
  seed/tests/test_audit_template.py
  seed/views/v3/organizations.py
Labels: Bug

#4755 Fix ubid preferred setting bug
  seed/static/seed/js/controllers/ubid_editor_modal_controller.js
Labels: Bug

#4732 Allow multiple ubids during import
  seed/models/properties.py
  seed/tests/test_ubids.py
Labels: Feature
