Repository SEED-platform/seed, pull requests merged in 2024-12, with the labels that each got.

#4885 Portfolio summary move to backend
  seed/migrations/0233_alter_goal_options.py
  seed/models/data_quality.py
  seed/models/goals.py
  seed/serializers/goals.py
  seed/static/seed/js/controllers/portfolio_summary_controller.js
  seed/static/seed/js/services/goal_service.js
  seed/static/seed/js/services/inventory_service.js
  seed/tests/test_goals.py
  seed/utils/inventory_filter.py
  seed/utils/search.py
  seed/views/v3/goals.py
Labels: Enhancement

#4894 Fix invalid permission class
  seed/views/v3/column_list_profiles.py
Labels: Bug

#4874 Fix notes modal
  seed/views/v3/organizations.py
Labels: Bug

#4890 Speed-up-program-and-property-insight-pages
  seed/models/compliance_metrics.py
  seed/static/seed/js/controllers/insights_property_controller.js
  seed/static/seed/js/controllers/program_setup_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/compliance_metric_service.js
  seed/static/seed/partials/insights_property.html
  seed/utils/properties.py
  seed/views/v3/compliance_metrics.py
Labels: Enhancement

#4851 Fix organization delete - ensure there is a chance to confirm and that it works in one step.
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.mo
  locale/es/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/static/seed/js/controllers/admin_controller.js
  seed/static/seed/js/controllers/confirm_organization_deletion_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/es.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/admin.html
  seed/static/seed/partials/confirm_organization_deletion_modal.html
  seed/tasks.py
  seed/templates/seed/_scripts.html
  seed/tests/test_tasks.py
  seed/views/v3/organizations.py
Labels: Bug

#4889 Redo group meter creation
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.mo
  locale/es/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  package-lock.json
  seed/serializers/meters.py
  seed/static/seed/js/controllers/group_meter_creation_modal_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_meters_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_systems_controller.js
  seed/static/seed/js/controllers/meter_deletion_modal_controller.js
  seed/static/seed/js/controllers/meter_edit_modal_controller.js
  seed/static/seed/js/controllers/system_meter_readings_upload_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/inventory_group_service.js
  seed/static/seed/js/services/uploader_service.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/es.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/group_meter_creation_modal.html
  seed/static/seed/partials/inventory_group_detail_meters.html
  seed/static/seed/partials/inventory_group_modal.html
  seed/static/seed/partials/inventory_groups_list.html
  seed/static/seed/partials/meter_edit_modal.html
  seed/static/seed/partials/service_modal.html
  seed/static/seed/partials/system_meter_readings_upload_modal.html
  seed/static/seed/partials/system_modal.html
  seed/static/seed/partials/systems_table.html
  seed/static/seed/scss/style.scss
  seed/templates/seed/_scripts.html
  seed/tests/data/system_meter_readings.xlsx
  seed/tests/test_inventory_groups.py
  seed/utils/meters.py
  seed/views/v3/import_files.py
  seed/views/v3/inventory_groups.py
  seed/views/v3/properties.py
Labels: Enhancement

#4875 Add button to show or hide all labels
  seed/static/seed/js/controllers/label_admin_controller.js
  seed/static/seed/js/services/label_service.js
  seed/static/seed/partials/label_admin.html
  seed/tests/test_labels.py
  seed/tests/test_labels_api_views.py
  seed/views/v3/labels.py
Labels: Feature

#4896 Add show all labels description text and translation
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.mo
  locale/es/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/es.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/label_admin.html
Labels: Enhancement

#4891 Add transactions template to portfolio summary
  seed/migrations/0234_transaction_goals.py
  seed/models/goals.py
  seed/serializers/goals.py
  seed/static/seed/js/controllers/goal_editor_modal_controller.js
  seed/static/seed/js/controllers/portfolio_summary_controller.js
  seed/static/seed/js/services/label_service.js
  seed/static/seed/partials/goal_editor_modal.html
  seed/static/seed/partials/portfolio_summary.html
  seed/tests/test_goals.py
  seed/utils/generic.py
  seed/utils/goals.py
  seed/utils/public.py
  seed/utils/search.py
  seed/views/v3/goals.py
Labels: Feature

#4903 Updated list of possible Audit Template reports in Org Settings
  seed/static/seed/js/controllers/organization_settings_controller.js
Labels: Enhancement

#4906 Mapping review and line length bug fixes
  seed/static/seed/js/controllers/mapping_controller.js
  seed/static/seed/js/controllers/program_setup_controller.js
Labels: Bug
