Repository SEED-platform/seed, pull requests merged in 2024-04, with the labels that each got.

#4612 Fix merge modal for all cycles
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/controllers/inventory_map_controller.js
  seed/static/seed/js/services/inventory_service.js
Labels: Bug

#4610 Geocode UBIDs using centroid
  seed/tests/test_utils_ubid.py
  seed/utils/ubid.py
Labels: Enhancement

#4613 Fix ubid bugs
  seed/data_importer/match.py
  seed/utils/merge.py
  seed/utils/ubid.py
Labels: Bug

#4609 Fix floating point rounding
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/js/controllers/inventory_list_controller.js
  seed/static/seed/js/filters/floatingPoint.js
  seed/static/seed/js/seed.js
  seed/static/seed/partials/inventory_detail.html
  seed/templates/seed/_scripts.html
Labels: Enhancement

#4586 Call spinner on default report export
  seed/static/seed/js/controllers/export_report_modal_controller.js
  seed/static/seed/js/controllers/inventory_reports_controller.js
Labels: Bug

#4595 Changes the dataview evaluate endpoint from put to post
  seed/static/seed/js/services/data_view_service.js
  seed/tests/test_data_view_views.py
  seed/views/v3/data_views.py
Labels: Bug

#4600 Enable blank filters for other inventory columns
  seed/utils/inventory_filter.py
Labels: Bug

#4585 Encrypt organization audit template password
  seed/audit_template/audit_template.py
  seed/lib/superperms/orgs/migrations/0031_encrypt_existing_audit_template_passwords.py
  seed/tests/test_audit_template.py
  seed/views/v3/organizations.py
Labels: Enhancement

#4623 Fixes bug to hide edit form on save
  seed/static/seed/js/controllers/inventory_detail_controller.js
Labels: Bug

#4626 Handle null values in related columns
  seed/static/seed/js/controllers/inventory_list_controller.js
Labels: Bug

#4611 Fix mapping previews for files with a single column
  seed/views/v3/import_files.py
Labels: Bug

#4599 Render scenario ui-grid on expand
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/partials/at_scenarios.html
Labels: Enhancement

#4637 Remove stale actions
  .github/workflows/stale-ice-box.yml
  .github/workflows/stale.yml
Labels: Maintenance, Do not publish

#4630 Speed up derived columns
  seed/models/derived_columns.py
  seed/views/v3/derived_columns.py
Labels: Enhancement

#4619 Speed up get labels
  seed/search.py
  seed/serializers/labels.py
  seed/tests/test_property_views.py
  seed/tests/test_taxlot_views.py
  seed/utils/labels.py
  seed/views/v3/labels.py
Labels: Enhancement

#4641 ensure is_ali_root is populated on redirects
  seed/static/seed/js/controllers/inventory_list_controller.js
Labels: Bug

#4625 Speed up filter groups
  seed/views/v3/filter_group.py
Labels: Maintenance

#4621 Speed up taxlot property serializer
  seed/models/tax_lot_properties.py
  seed/views/v3/filter_group.py
Labels: Enhancement

#4638 Dont dupe inventory rows
  seed/utils/inventory_filter.py
Labels: Bug

#4628 Speed up get column list profile
  seed/views/v3/column_list_profiles.py
Labels: Enhancement

#4607 Dont call get inventory twice on cycle update
  seed/static/seed/js/controllers/inventory_list_controller.js
Labels: Enhancement

#4631 Speed up column list
  seed/models/columns.py
Labels: Enhancement

#4643 Updated homepage background
  docs/source/data_model.rst
  docs/source/images/case-a.png
  docs/source/images/case-a.webp
  docs/source/images/case-abcd.png
  docs/source/images/case-abcd.webp
  docs/source/images/case-b.png
  docs/source/images/case-b.webp
  docs/source/images/case-c.png
  docs/source/images/case-c.webp
  docs/source/images/case-d.png
  docs/source/images/case-d.webp
  docs/source/images/data-model.png
  docs/source/images/data-model.webp
  seed/docs/faq/features/map-merge-link.md
  seed/docs/static/docs/images/mapping_diagram.png
  seed/docs/static/docs/images/mapping_diagram.webp
  seed/landing/static/landing/images/landing/bg-paper.png
  seed/landing/static/landing/images/landing/bg-paper.webp
  seed/landing/static/landing/images/landing/landing-bg.png
  seed/landing/static/landing/images/landing/landing-bg.webp
  seed/landing/static/landing/images/landing/logo-chrome-64.png
  seed/landing/static/landing/images/landing/logo-firefox-64.png
  seed/landing/static/landing/images/landing/logo-ie-64.png
  seed/landing/static/landing/images/landing/logo-safari-64.png
  seed/landing/static/landing/js/landing.js
  seed/landing/static/landing/scss/landing.scss
  seed/static/seed/images/bg_first_td.png
  seed/static/seed/images/bg_first_td.webp
  seed/static/seed/scss/style.scss
Labels: Enhancement

#4636 Speed up stats
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/models/columns.py
  seed/static/seed/js/controllers/inventory_summary_controller.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/inventory_nav.html
  seed/views/v3/analyses.py
Labels: Enhancement

#4644 Update pre-commit versions
  .github/release.yml
  .github/workflows/ci.yml
  .github/workflows/pr-labels.yml
  .github/workflows/publish.yml
  .pre-commit-config.yaml
  charts/persistentvolumes/values.yaml
  charts/seed/values.yaml
  charts/values.yaml
  seed/landing/static/landing/scss/landing.scss
  seed/static/seed/scss/style.scss
Labels: Do not publish

#4645 Better update
  seed/analysis_pipelines/better/pipeline.py
  seed/static/seed/js/controllers/inventory_detail_analyses_controller.js
  vendors/package-lock.json
Labels: Bug

#4647 alternative way to get used cols for sharing page
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/analyses_service.js
  seed/static/seed/scss/style.scss
  seed/views/v3/analyses.py
Labels: Enhancement

#4646 Improve Column list profile creation
  seed/static/seed/js/controllers/inventory_settings_controller.js
  seed/tests/test_column_list_profiles_views.py
Labels: Enhancement
