Repository SEED-platform/seed, pull requests merged in 2024-06, with the labels that each got.

#4677 On click go to property
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/views/v3/organizations.py
Labels: Enhancement

#4693 New flip axis
  seed/static/seed/js/controllers/inventory_reports_controller.js
Labels: Feature

#4648 Speed-up-organization-report
  seed/views/v3/organizations.py
Labels: Enhancement

#4696 Lock Numpy
  requirements/base.txt
Labels: Bug

#4653 filter report by ali
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/inventory_reports_service.js
  seed/static/seed/partials/inventory_reports.html
  seed/static/seed/scss/style.scss
  seed/tests/test_organization_views.py
  seed/tests/test_salesforce_views.py
  seed/views/v3/organizations.py
Labels: Enhancement

#4699 Node dependency upgrade
  package-lock.json
  package.json
  vendors/package-lock.json
Labels: Maintenance

#4706 Fix several AH meter issues
  seed/tests/test_meter_views.py
  seed/utils/api_schema.py
  seed/utils/viewsets.py
  seed/views/v3/building_files.py
  seed/views/v3/gbr_properties.py
  seed/views/v3/meter_readings.py
  seed/views/v3/meters.py
  seed/views/v3/property_views.py
Labels: Bug

#4691 Allow org setting default report axis options
  package-lock.json
  package.json
  seed/migrations/0218_auto_20240604_1605.py
  seed/models/columns.py
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/static/seed/js/controllers/organization_settings_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/partials/organization_settings.html
  seed/static/seed/tests/settings_controller.spec.js
  seed/tests/test_account_views.py
  seed/tests/test_api.py
  seed/tests/test_meter_views.py
  seed/tests/test_organization_views.py
  seed/tests/test_reports.py
  seed/utils/api_schema.py
  seed/utils/viewsets.py
  seed/views/v3/building_files.py
  seed/views/v3/gbr_properties.py
  seed/views/v3/meter_readings.py
  seed/views/v3/meters.py
  seed/views/v3/organizations.py
  seed/views/v3/property_views.py
  vendors/package-lock.json
Labels: Feature

#4670 Add public geojson endpoint
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/api/v3/urls.py
  seed/lib/superperms/orgs/migrations/0033_organization_public_geojson_enabled.py
  seed/lib/superperms/orgs/models.py
  seed/static/seed/js/controllers/organization_sharing_controller.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/cycle_admin.html
  seed/static/seed/partials/organization_settings.html
  seed/static/seed/partials/organization_sharing.html
  seed/static/seed/scss/style.scss
  seed/tests/test_account_views.py
  seed/tests/test_public_views.py
  seed/utils/public.py
  seed/views/v3/organizations.py
  seed/views/v3/public.py
  seed/views/v3/tax_lot_properties.py
Labels: Feature

#4685 Create public feed endpoints
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/api/v3/urls.py
  seed/lib/superperms/orgs/migrations/0032_organization_public_feed.py
  seed/lib/superperms/orgs/migrations/0033_organization_public_geojson_enabled.py
  seed/lib/superperms/orgs/models.py
  seed/models/properties.py
  seed/models/tax_lots.py
  seed/static/seed/js/controllers/organization_sharing_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/analyses_service.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/fr_CA.json
  seed/static/seed/partials/cycle_admin.html
  seed/static/seed/partials/organization_settings.html
  seed/static/seed/partials/organization_sharing.html
  seed/static/seed/scss/style.scss
  seed/tests/test_account_views.py
  seed/tests/test_public_views.py
  seed/utils/public.py
  seed/utils/ubid.py
  seed/views/v3/analyses.py
  seed/views/v3/organizations.py
  seed/views/v3/public.py
  seed/views/v3/tax_lot_properties.py
Labels: Feature
