Repository SEED-platform/seed, pull requests merged in 2025-09, with the labels that each got.

#5061 Fix export race condition
  seed/static/seed/js/services/inventory_service.js
  seed/utils/tax_lot_properties.py
Labels: Bug

#5090 Add option to change meter names
  seed/static/seed/js/controllers/inventory_detail_meters_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_meters_controller.js
  seed/static/seed/js/controllers/meter_edit_modal_controller.js
  seed/static/seed/js/services/meter_service.js
  seed/static/seed/partials/meter_edit_modal.html
  seed/tests/data/system_meter_readings.xlsx
  seed/tests/test_meter_views.py
  seed/views/v3/inventory_groups.py
  seed/views/v3/meters.py
Labels: Enhancement

#5093 Omit field from state during import
  seed/data_importer/tasks.py
  seed/utils/import_file.py
Labels: Bug

#5097 Groups sankey
  seed/static/seed/js/controllers/inventory_group_detail_dashboard_controller.js
  seed/static/seed/js/controllers/inventory_group_detail_meters_controller.js
  seed/static/seed/js/controllers/service_meter_creation_modal_controller.js
  seed/static/seed/js/seed.js
  seed/static/seed/js/services/inventory_group_service.js
  seed/static/seed/partials/inventory_group_detail_dashboard.html
  seed/static/seed/partials/inventory_group_detail_meters.html
  seed/static/seed/partials/service_meter_creation_modal.html
  seed/static/seed/scss/style.scss
  seed/templates/seed/_vendor_scripts.html
  seed/tests/data/system_meter_readings.xlsx
  seed/views/v3/import_files.py
  seed/views/v3/inventory_groups.py
  seed/views/v3/services.py
  vendors/package-lock.json
  vendors/package.json
Labels: Feature

#5101 Fix meter creation
  seed/views/v3/services.py
Labels: Bug
