Repository SEED-platform/seed, pull requests merged in 2025-01, with the labels that each got.

#4917 Fix upgrade recommendation
  seed/analysis_pipelines/upgrade_recommendation.py
Labels: Bug

#4923 Add meter of type Electric to BSyncR analysis
  seed/analysis_pipelines/bsyncr.py
Labels: Enhancement

#4920 Remove inventory list `Data` nav item
  CHANGELOG.md
  seed/static/seed/partials/inventory_nav.html
Labels: Maintenance

#4927 Remove server settings from the session cookie
  seed/landing/forms.py
  seed/landing/templates/two_factor/core/login.html
  seed/landing/views.py
Labels: Maintenance

#4905 save changes prompt
  seed/static/seed/js/controllers/column_mappings_controller.js
  seed/static/seed/js/controllers/organization_settings_controller.js
  seed/static/seed/js/controllers/two_factor_profile_controller.js
Labels: Enhancement

#4926 Add Simple JWT to authorization setup
  config/settings/common.py
  config/urls.py
  requirements/base.txt
  seed/landing/models.py
  seed/landing/serializers.py
Labels: Enhancement

#4909 Portfolio Summary Updates
  seed/static/seed/js/controllers/portfolio_summary_controller.js
  seed/static/seed/partials/portfolio_summary.html
  seed/static/seed/scss/style.scss
Labels: Enhancement

#4932 Fixes inventory groups add inventory bug
  seed/static/seed/js/controllers/update_inventory_groups_modal_controller.js
  seed/static/seed/js/services/organization_service.js
  seed/static/seed/partials/update_inventory_groups_modal.html
  seed/tests/test_organization_access_levels.py
  seed/views/v3/access_levels.py
Labels: Bug

#4924 Show default display name on analyses
  seed/models/properties.py
  seed/serializers/analysis_property_views.py
  seed/static/seed/js/controllers/analysis_controller.js
  seed/static/seed/js/controllers/analysis_run_controller.js
  seed/static/seed/js/controllers/inventory_detail_analyses_controller.js
  seed/static/seed/partials/analysis_runs.html
Labels: Bug

#4919 Make data type column wide enough to see completely
  seed/static/seed/partials/mapping.html
Labels: Bug

#4936 Django settings endpoint
  config/urls.py
  seed/landing/models.py
  seed/views/main.py
Labels: Feature

#4937 Fix group meter interval
  seed/static/seed/js/controllers/inventory_group_detail_meters_controller.js
Labels: Bug

#4939 Move JWT token claims to v3_users_current
  seed/landing/serializers.py
  seed/views/v3/users.py
Labels: Enhancement
