Repository SEED-platform/seed, pull requests merged in 2025-03, with the labels that each got.

#4947 remove appfleet config
  .gitignore
  appfleet-config/.gitignore
  appfleet-config/Makefile
  appfleet-config/appfleet.yml
  appfleet-config/buildspec.yml
  appfleet-config/create-credentials.sh
  appfleet-config/docker-compose.deploy.yaml
  appfleet-config/generate_appfleet_tag_overrides.sh
  appfleet-config/nginx.conf
  release.sh
Labels: Bug

#4949 Modified AT Export: Truncate zipcode to 5 digits and handle SentenceCasing HVAC
  seed/audit_template/audit_template.py
Labels: Bug, Army

#4948 Add AL to insights page charts
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/tests/test_reports.py
  seed/views/v3/organizations.py
Labels: Enhancement, Army

#4950 Download capability of audit template xml file
  seed/analysis_pipelines/better/buildingsync.py
  seed/audit_template/audit_template.py
  seed/static/seed/js/controllers/inventory_detail_controller.js
  seed/static/seed/partials/inventory_detail.html
  seed/views/v3/audit_template.py
  seed/views/v3/organizations.py
Labels: Enhancement

#4952 Fix
  seed/views/v3/organizations.py
Labels: Bug

#4955 Fix groups meters property column
  seed/serializers/meters.py
  seed/static/seed/js/controllers/inventory_group_detail_meters_controller.js
  seed/tests/test_property_views.py
Labels: Bug

#4959 Fix ESPM download, change generateData from POST to GET
  seed/views/v3/portfolio_manager.py
Labels: Bug
