Repository SEED-platform/seed, pull requests merged in 2025-02, with the labels that each got.

#4940 Add user serializer
  seed/landing/models.py
  seed/serializers/users.py
  seed/tests/test_account_views.py
  seed/tests/test_api.py
  seed/views/v3/users.py
Labels: Enhancement

#4929 Fix compliance filter groups
  seed/models/compliance_metrics.py
  seed/models/filter_group.py
  seed/utils/properties.py
Labels: Bug

#4922 Add Temperature meters
  seed/data_importer/meters_parser.py
  seed/data_importer/tests/test_meters_parser.py
  seed/data_importer/utils.py
  seed/migrations/0242_add_meter_types.py
  seed/models/meters.py
Labels: Feature

#4941 Add Federal Energy and Water Audit Report
  seed/static/seed/js/controllers/organization_settings_controller.js
Labels: Enhancement

#4944 remove address, city, state requirements for AT export
  seed/audit_template/audit_template.py
  seed/tests/test_audit_template.py
Labels: Enhancement
