Repository SEED-platform/seed, pull requests merged in 2025-05, with the labels that each got.

#4982 Fix bsyncr xml timeseries ordering
  seed/analysis_pipelines/bsyncr.py
Labels: Bug

#4977 Update element table
  requirements/base.txt
  seed/lib/tkbl/tkbl.py
  seed/static/seed/partials/inventory_detail.html
  seed/views/v3/elements.py
Labels: Enhancement

#4987 fix AT test broken by TKBL update
  seed/tests/test_audit_template.py
Labels: Bug

#4985 Fix `used_columns` error for taxlots
  seed/views/v3/analyses.py
Labels: Bug

#4986 Join related column values during export
  seed/tests/test_tax_lot_property.py
  seed/views/v3/tax_lot_properties.py
Labels: Bug

#4990 Update EISA432 and Scope 1 emission code enums. Set order of bars in default reports charts for categorical data
  locale/en_US/LC_MESSAGES/django.mo
  locale/en_US/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.mo
  locale/es/LC_MESSAGES/django.po
  locale/fr_CA/LC_MESSAGES/django.mo
  locale/fr_CA/LC_MESSAGES/django.po
  seed/analysis_pipelines/element_statistics.py
  seed/analysis_pipelines/upgrade_recommendation.py
  seed/audit_template/audit_template.py
  seed/lib/tkbl/tkbl.py
  seed/static/seed/js/controllers/inventory_reports_controller.js
  seed/static/seed/locales/en_US.json
  seed/static/seed/locales/es.json
  seed/static/seed/locales/fr_CA.json
  seed/tests/test_audit_template.py
  seed/views/v3/elements.py
  seed/views/v3/organizations.py
Labels: Enhancement

#4972 Remove developer logs
  seed/views/v4/organization_users.py
Labels: Bug

#4978 Adds a record count endpoint
  seed/api/v4/urls.py
  seed/tests/v4/test_analyses_views.py
  seed/tests/v4/test_taxlot_property_views.py
  seed/views/v3/analyses.py
  seed/views/v4/analyses.py
  seed/views/v4/organization_users.py
  seed/views/v4/taxlot_properties.py
Labels: Feature, angular

#4992 Fix report chart
  seed/static/seed/js/controllers/inventory_reports_controller.js
Labels: Bug

#5000 Fix scatter chart ordering for all browsers
  seed/static/seed/js/controllers/inventory_reports_controller.js
Labels: Bug
