Repository SEED-platform/seed, pull requests merged in 2025-04, with the labels that each got.

#4958 Update BuildingSync to version 2.6.0
  config/settings/common.py
  docs/source/buildingsync.rst
  requirements/base.txt
  seed/analysis_pipelines/better/buildingsync.py
  seed/audit_template/audit_template.py
  seed/building_sync/building_sync.py
  seed/building_sync/enumerations/enumerations_v1_0_0.json
  seed/building_sync/enumerations/enumerations_v2_6_0.json
  seed/building_sync/schemas/BuildingSync_v2_6_0.xsd
  seed/building_sync/tests/data/ex_1_v2.6.0.xml
  seed/building_sync/tests/test_buildingsync_views.py
  seed/building_sync/validation_client.py
  seed/data_importer/tests/test_match_incoming.py
  seed/lib/superperms/orgs/models.py
  seed/migrations/0243_update_bsync_measures_v2_6_0.py
  seed/models/building_file.py
  seed/models/measures.py
  seed/tests/data/bps/BPS_Sample_AT_11911.xml
  seed/tests/data/bps/BPS_Sample_AT_12227.xml
  seed/tests/data/bps/BPS_Sample_AT_17971.xml
  seed/tests/data/bps/BPS_Sample_AT_21368.xml
  seed/tests/data/bps/BPS_Sample_AT_21378.xml
  seed/tests/data/bps/BPS_Sample_AT_21381.xml
  seed/tests/data/bps/BPS_Sample_AT_21404.xml
  seed/tests/data/bps/BPS_Sample_AT_21405_2019.xml
  seed/tests/data/bps/BPS_Sample_AT_21405_2020.xml
  seed/tests/data/bps/BPS_Sample_AT_21405_2021.xml
  seed/tests/data/bps/BPS_Sample_AT_21426.xml
  seed/tests/data/bsync_export_to_at_with_meters_measures.xml
  seed/tests/data/building_sync_xml.txt
  seed/tests/test_measures.py
  seed/views/v3/measures.py
Labels: Enhancement

#4967 Update precommit, a few dependencies, and spelling issues
  .cspell.json
  .pre-commit-config.yaml
  config/settings/common.py
  package-lock.json
  requirements/test.txt
  seed/analysis_pipelines/better/client.py
  seed/analysis_pipelines/better/pipeline.py
  seed/analysis_pipelines/bsyncr.py
  seed/audit_template/audit_template.py
  seed/building_sync/building_sync.py
  seed/building_sync/mappings.py
  seed/data_importer/equivalence_partitioner.py
  seed/data_importer/tasks.py
  seed/exception_handler.py
  seed/lib/mcm/cleaners.py
  seed/lib/mcm/reader.py
  seed/lib/progress_data/progress_data.py
  seed/lib/superperms/orgs/decorators.py
  seed/lib/superperms/orgs/permissions.py
  seed/management/commands/add_mapping_profile.py
  seed/management/commands/add_member_to_org.py
  seed/migrations/0059_auto_20170407_1516.py
  seed/migrations/0101_auto_20190318_1835.py
  seed/migrations/0119_column_recognize_empty.py
  seed/models/building_file.py
  seed/models/columns.py
  seed/models/compliance_metrics.py
  seed/models/data_quality.py
  seed/models/measures.py
  seed/models/properties.py
  seed/models/tax_lots.py
  seed/search.py
  seed/tasks.py
  seed/test_helpers/fake.py
  seed/tests/test_audit_template.py
  seed/tests/test_columns.py
  seed/tests/test_decorators.py
  seed/tests/test_derived_columns.py
  seed/tests/test_numeric_expression_parser.py
  seed/tests/test_portfoliomanager.py
  seed/tests/test_string_expression_parser.py
  seed/utils/generic.py
  seed/utils/labels.py
  seed/utils/public.py
  seed/utils/v4/inventory_filter.py
  seed/views/v3/audit_template_configs.py
  seed/views/v3/columns.py
  seed/views/v3/data_views.py
  seed/views/v3/filter_group.py
  seed/views/v3/inventory_group_mappings.py
  seed/views/v3/organizations.py
  seed/views/v3/portfolio_manager.py
  seed/views/v3/properties.py
  seed/views/v3/public.py
  seed/views/v3/taxlots.py
  seed/views/v3/users.py
Labels: Maintenance

#4966 Use case-insensitive lookup of username in the API
  seed/landing/models.py
  seed/static/seed/partials/developer.html
Labels: Bug

#4973 Update bsyncr to use version 2.6.0 of BuildingSync
  .cspell.json
  .pre-commit-config.yaml
  docs/source/buildingsync.rst
  seed/analysis_pipelines/bsyncr.py
  seed/tests/test_analysis_pipelines.py
Labels: Enhancement

#4956 Updated BETTER BuildingSync Mappings
  seed/analysis_pipelines/better/buildingsync.py
Labels: Enhancement
